### ISSUE TITLE
Error in connection_string.js when run the node simple-sample-http.js app.

### ISSUE THREAD

**Issue by NNM11** [Azure/azure-iot-sdks#140]
### Issue:
I followed the instruction of the Azure-IoT-sdks (https://github.com/Azure/azure-iot-sdks/blob/master/node/device/doc/run_sample.md'  to run the sample 'simple_sample_http.js'.  
The app failed to run with error in the connection_string.js.   Any idea?

#### Environment:
- Ubuntu 14.4 - 64bits. 
- Latest azure-iot-sdks (11/17/15)

###### the device was provisioned as:
-----
 deviceId:                  device-id
  generationId:               635833962783760024
  etag:                       MA==
  connectionState:            Disconnected
  status:                     enabled
  statusReason:               null
  connectionStateUpdatedTime: 0001-01-01T00:00:00
  statusUpdatedTime:          0001-01-01T00:00:00
  lastActivityTime:           0001-01-01T00:00:00
  cloudToDeviceMessageCount:  0
  authentication: 
    SymmetricKey: 
      primaryKey:   xxxxxx
      secondaryKey: zzzzzz

----
######  setup an IoT hub instance and ran the iothub-explorer to monitor the new device added.
---
###### Set the connection string xxxxxx=' for the sample app

*Run*
*$ npm install
$ node simple_sample_http.js

.../node_modules/azure-iot-common/lib/connection_string.js:21
    if (!(key in dict)) throw new ArgumentError(err + key);
                              ^
ERROR

**Comment by pierreca** [comment]
Looks like you're using a key instead of a connection string in the sample app. Can you confirm the connection string you pasted in place of [IoT Device Connection String] in simple_sample_http.js is formatted such as:HostName=*hub-name*.azure-devices.net;DeviceId=*device-id*;SharedAccessKey=*key* ?

To obtain the device connection string you can use either [iothub-explorer](https://github.com/Azure/azure-iot-sdks/blob/master/tools/iothub-explorer/doc/provision_device.md) or the [DeviceExplorer app](https://github.com/Azure/azure-iot-sdks/blob/master/tools/DeviceExplorer/doc/how_to_use_device_explorer.md)

Last but not least, I would strongly advise against disclosing any key/connectionstring in issues you submit (they are public), and I would suggest you delete and recreate the iothub instance :)

**Comment by NNM11** [comment]
Yes - using the DEVICE connection-string fixed it.  Thx.

BTW - The steps in  provision_device.md should make this clearer.  Also it would be useful if the connection-string.js validates and warns about the missing element of the connection-string as part of the error.  

* Run this command to get the DEVICE connection-string:
$ node iot-hub-explorer.js  <hub-connection-string> get <device-id> --connection-string

**Comment by dominicbetts** [comment]
Updated provision_device.md. @tameraw please close when the PR has been accepted.

**Comment by tameraw** [comment]
PR merged. Thanks.

**Comment by Chucky89** [comment]
I ran into the same error, maybe correct the tutorial for the future.
