### ISSUE TITLE
Azure IoT SDK simplesample_http for CC3200 - IoT Hubs Connection Error

### ISSUE THREAD

**Issue by Mahawili** [Azure/azure-iot-sdks#155]
Hi, 

I'm having trouble getting the simplesample_http example -- provided as part of the Azure IoT SDK for the TI CC3200 -- to connect to my IoT hub.  I followed the instructions found on the GitHub page for the CC3200.  I created a new device and provisioned it using Device Explorer and the instructions found on the corresponding GitHub page.  I've included the proper User Step information for the current date-time macros, WIFI SSID and SECURITY_KEY macros, and the device-specific connection string.  The example compiles and flashes to the device without issue.  I have also flashed the provided certificate to the CC3200 to /cert/ms.der as required.  

During startup, I observe the following through my terminal emulator.  I added a few more Error print points of my own to track what was being executed.  For example, lines 383 and 448 of httpapiex.c are not errors per-se, but merely extra indicators to show where the program has been.  

Starting the simplesample_http example
 CC3200 has connected to AP and acquired an IP address.
 IP Address: XXX.XXX.X.XXX
 Info: IoT Hub SDK for C, version 1.0.0-preview.6
 Line 198: IoTHubClient accepted the message for delivery

Error: Time:Wed Aug 23 09:48:40 2028 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:383 HTTPAPI_Init() == HTTPAPI_OK
 Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:448 the program has been hereError: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:392 handleData->httpHandle = HTTPAPI_CreateConnection(STRING_c_str(handleData->hostName))) == NULL
 Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:462 handleData->k is 0Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:478 handleData->k is defaultError: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:486 unable to recover sending to a working state
 Error: Time:Thu May 13 16:10:32 2032 File:../../src/iothubtransporthttp.c Func:DoEvent Line:1206 unable to HTTPAPIEX_ExecuteRequest
 Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:383 HTTPAPI_Init() == HTTPAPI_OK
 Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:448 the program has been hereError: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:392 handleData->httpHandle = HTTPAPI_CreateConnection(STRING_c_str(handleData->hostName))) == NULL
 Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:462 handleData->k is 0Error: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:478 handleData->k is defaultError: Time:Thu May 13 16:10:32 2032 File:../../src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:486 unable to recover sending to a working state
 Error: Time:Thu May 13 16:10:32 2032 File:../../src/iothubtransporthttp.c Func:DoMessages Line:1428 unable to HTTPAPIEX_ExecuteRequest

One thing I noticed right away is that the timestamps are years off, so I double-checked the date-time macros in main.c, and they are correct.  I don't see any calls to an SNTP server in the program, and I don't know what is generating these timestamps, but I wonder if they are either part of the cause or symptomatic of the core problem.   Reading through the errors, it looks like HTTPAPI_Init() successfully completes, but HTTPAPI_CreateConnection() does not.  The error on Line 392 of httpapiex.c indicates that the hostname is NULL.  It's my understanding that this should be assigned from the parsed connection string in simplesample_http.c, which must have completed OK since I get no errors from the IoTHubClient_LL_CreateFromConnectionString() parser in iothub_client_ll.c.   Yet something isn't lining up.  Can you please provide some guidance as to where the issue may be occurring?  

I have also attached my modified httpapiex.c (renamed httpapiex.txt so I could upload it) so that line numbers in my terminal printouts match the code if anyone tries to recreate this issue.  (only modifications are added Error prints for debugging) 

[httpapiex.txt](https://github.com/Azure/azure-iot-sdks/files/43477/httpapiex.txt)

Thanks for your time and assistance. 

-David

**Comment by tisb-vikram** [comment]
David, 

Is your CC3200 device connected to the network behind a proxy/firewall?The host name resolution will fail behind the proxy/firewall. Currently, we don't have proxy support for CC3200 on azure-iot-sdk.

Regarding date-time, this is a known issue. The CC3200 device has two subsystems: Applications Micro-controller and WiFi Network Processor. The date-time macros in main.c will set up the system clock in the WiFi Network Processor and the time stamp in your prints is from the Applications subsystem where the system clock is not setup. We will address this issue in the next push to azure-iot-sdks github from TI.

Vikram Adiga
Texas Instruments

**Comment by Mahawili** [comment]
Hi Vikram,

Thanks for your reply.  To the best of my ability, I have confirmed that a proxy/firewall is not the issue.  I tried connecting to an unprotected open network instead of the one I normally use.  The CC3200 connected to the new AP without issue, but there was no change in the subsequent host connection errors.  I returned to using my original AP, but logged into my modem and removed all firewalls, confirmed that no proxy was being used, and removed any VPN settings that were selected.  I did these in sequence, testing the device with each new setting configuration, but to no avail.  I suppose there could be some sort of firewall on my modem, but I don't have access to those configurations with my current provider.  However, it may be important to note that all of the original (non-Azure) CC3200 Launchpad SDK's provided by TI work without issue.  

The timestamp issue makes a lot of sense.  I forgot about the clock on the application MCU.  

Do you have any other suggestions?  

Thanks, 
-David

**Comment by tisb-vikram** [comment]
Hi David,

Since you are able to run non-Azure examples on CC3200 Launchpad, I would check the device connection string again and also try connecting to the host server from PC on the same network just to make sure the host name is getting resolved on the network.

Vikram

**Comment by snobu** [comment]
David, 

Two things here, 

>However, it may be important to note that all of the original (non-Azure) CC3200 Launchpad SDK's >provided by TI work without issue.

Not sure if that includes a HTTP client sample, but here's one
http://processors.wiki.ti.com/index.php/CC32xx_HTTP_Client_Demo

It's worth trying to point it to a non-TLS website like http://www.linux.org and see if you get a `200 OK` back. This would rule out a connectivity problem to the outside world (name resolution included).

Now, Azure IoT Hub only listens on 443/TCP for a TLS handshake. Plain old `HTTP` is not supported.

Here's a port probe on both 80 and 443/TCP for my IoT Hub endpoint:

```bash
# nmap -p 80,443 heresthething.azure-devices.net

Starting Nmap 6.47 ( http://nmap.org ) at 2015-12-03 23:51 GTB Standard Time
Initiating Ping Scan at 23:51
Scanning heresthething.azure-devices.net (40.127.132.17) [4 ports]

Nmap scan report for heresthething.azure-devices.net (40.127.132.17)
Host is up (0.063s latency).
PORT    STATE    SERVICE
80/tcp  filtered http
443/tcp open     https
```

Now giving that your clock skew is quite bad - two decades off to be precise - a TLS handshake with certificate validation will certainly fail there when your CC3200 will try to compare the expiration date on the cert with current datetime.

```bash
# curl -kvs https://heresthething.azure-devices.net

* About to connect() to heresthething.azure-devices.net port 443 (#0)
[..]
* Server certificate:
*        subject: CN=*.azure-devices.net
*        start date: 2015-08-27 03:18:04 GMT
*        expire date: 2017-08-26 03:18:04 GMT
*        issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT SSL SHA2
```
Since the `*azure-devices.net` certificate expires somewhere in 2017.

Not sure if you can disable certificate validation but - and of course it's just me now assuming it's the reason for your connection error - maybe there's a way to setup both system clocks to at least the right year.

**Comment by dcristoloveanu** [comment]
I was able to repro the same issue you are having regarding connectivity on one of the routers I am using.

After some debugging it turned out that I was getting an error -161 in sl_NetAppDnsGetHostByName (basically saying no DNS server).
There are some similar reports on the TI site and after some digging I decided to update to the latest service pack.
Here is the thread that pointed me in that direction: http://e2e.ti.com/support/wireless_connectivity/simplelink_wifi_cc31xx_cc32xx/f/968/p/351524/1416590

The servicepack for the CC3200 can be downloaded here: http://www.ti.com/tool/cc3200sdk
I used CCS Uniflash to flash the service pack firmware binary and after that the simplesample_http worked.

I also added logging in the TI HTTPAPI adapter so that it prints out the return values for the HTTP APIs.
Could you please switch to the latest develop branch, program the latest service pack with Uniflash and post the result? I'll try to help debug further if you still have issues.

/Dan
P.S. After switching to develop, make sure you run "git submodule init" and "git submodule update" before rebuilding everything, in order to get the latest dependent azure-c-shared-utility submodule.

**Comment by tameraw** [comment]
Post provided from @dcristoloveanu. Closing issue and please feel free to reopen or create a new issue if still having any problems. Thanks!
