### ISSUE TITLE
Typescript definition file for node implementation

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#181]
It would be great to have a definitely typed definition file for using the IoT Node SDK with TypeScript.

**Comment by damienpontifex** [comment]
The choice to be written in straight javascript vs Typescript intrigues me if anyone on the project has some insights? 

I'm starting to use more Typescript in my development and it would be interesting to see why sometimes Microsoft projects choose straight javascript over Typescript rather than being critical of any tool observations.

**Comment by olivierbloch** [comment]
Hi @damienpontifex
The primary objective of the SDK is to offer something most of the developers out there will be familiar with so that they can use, re-use and adapt easily to their own specific needs.
We do not exclude to have a typescript implementation in the future but preferred starting with JavaScript and work closely with developers to provide what they need.
Hope this answers the question

**Comment by damienpontifex** [comment]
Thanks @olivierbloch make sense. I hadn't taken into account the barrier that TypeScript could potentially impose over JS.
Thanks for the feedback.

**Comment by ritave** [comment]
Reopening this issue, because implementation != definition files. The whole library can be written and Javascript but include Typescript typings for easier usage in that language.
