### ISSUE TITLE
The link for - Microsoft Azure IoT device SDK for .NET is broken

### ISSUE THREAD

**Issue by matlus** [Azure/azure-iot-sdks#228]
The link in this page
[Microsoft Azure IoT device SDK for .NET](https://github.com/Azure/azure-iot-sdks/blob/master/doc/csharp/device/readme.md)

Where can I get the .NET SDK for Azure IoT? Also the information on that page needs to be updated to include the fact that AMQP is supported. (I think)

**Comment by olivierbloch** [comment]
@matlus , can you please indicate which page you are referring to so that we can fix the broken link.
Also, there are 2 C# SDKs, one for device clients, used to connect devices to Azure IoT Hub, and one for service clients, used to develop applications to manage the service (adding/removing devices, monitoring messages,...).
The device client SDK for C# only supports HTTP at this point and can be found here: https://github.com/Azure/azure-iot-sdks/tree/master/csharp/device
The service client SDK for C# indeed uses both HTTP and AMQP because of the intrinsic nature of the service SDK APIs. Note that the service client SDK can only be used on .NET, it doesn't support .NET Micro Framework, nor Windows Embedded Compact, nor Universal Windows Apps

**Comment by pierreca** [comment]
The correct link is https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/readme.md 
The link is correct on the main page, not sure which page contains the broken link.

**Comment by matlus** [comment]
This link is on this page [Azure IoT SDKs/Readme!]
(https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/readme.md)

**Comment by matlus** [comment]
>The device client SDK for C# supports HTTP and AMQP for most platforms except for UWP that supports only HTTP at this point. 

Are there plans to support AMQP for Device Clients on the UWP and .NET Micro frameworks?

**Comment by tameraw** [comment]
@matlus - Yes we currently have captured in our backlog support for AMQP in the Device Client for the UWP & .NET Micro frameworks. We do not have exact ETA at this time.

Also the links in the document that you referred to have been fixed. Please let us know if you're still having issues with that. Thanks.

**Comment by matlus** [comment]
@tameraw , great news (on both counts). Thank you!
