### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by Akashdeep-Sarin** [Azure/azure-iot-sdks#259]
Hello guys,
I am installing iot-hub-sdk on my machine(Windows 7).
- Java 1.8
- Service SDK

Issue -1
While trying to build Qpid-proton . the build fails
Resolved : Using the following command
$ mvn -DskipTests install

Concern: Why is this not mentioned in guide ?

Issue -2
Iothub service sdk fails
After mvn install : 
    git clone https://github.com/Azure/azure-iot-sdks.git
    cd azure-iot-sdks/java/service
    mvn install

Screenshot:
![image](https://cloud.githubusercontent.com/assets/16319756/12672356/b17b1b00-c69b-11e5-9269-5649f87f9542.png)

Please Help

**Comment by tameraw** [comment]
@Akashdeep-Sarin - Thank you for reporting the issue. We're investigating and will update you soon.

**Comment by iluican** [comment]
Hi Akashdeep,

Thank you very much for taking the time to report these issues to us.

I will update the guide to reflect the fix for the qpid-proton build, and I'm working on a fix for the second issue.

Ilie.

**Comment by iluican** [comment]
Hi again,

I fixed the second issue. Now mvn install/verify will not yield any error. Please make sure to checkout the develop branch in order to see the fix, or wait until our next release to see this in master.

Regarding the first issue, I'm a bit confused: where exactly do we recommend building qpid-proton? We get the dependencies from maven, so there is no need for you to build it from source.

Thank you,
Ilie.

**Comment by tameraw** [comment]
@Akashdeep-Sarin - Closing. Please feel free to reopen if still having issues. Thanks.
