### ISSUE TITLE
Way to increase send timeouts

### ISSUE THREAD

**Issue by Praburaj** [Azure/azure-iot-sdks#276]
```
System.TimeoutException: Failed to get response for request: iothub.my-test-iot.14901.17ce50fc/7d83cda8-ce30-45a5-8338-cbac0287a95d/3e7286d7-5077-448d-aff3-d6e5ba14dfef
Tracking Id:9cd41a02625a441599dff2466928de0e-G:3-TimeStamp:02/02/2016 17:57:41
   at Microsoft.Azure.Devices.Client.AmqpDeviceClient.<SendAmqpMessageAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.AmqpDeviceClient.<OnSendEventAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClientHelper.<SendEventAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

I'm working on a scenario where a lot of clients are sending messages to IoTHub. However I see a lot of clients are running into a timeout exception after `1 min`. Is there a way to adjust the send timeout? 

I use the default `Amqp` transport for sending events.

**Comment by rajeevmv** [comment]
This is not supported at the moment. However, we have recently introduced an AmqpTransportSettings class to handle such configurations. The source code can be easily enhanced to support this. Feel free to make this change and submit a pull request.

**Comment by tameraw** [comment]
@Praburaj - The C client introduced a per/message timeout that can be controlled from the users code. Other clients will follow at some point. Contributions are always welcomed.

**Comment by jamescmaki** [comment]
Is there any documentation on messageTimeout? I am setting messageTimeout to 1000. After call to IoTHubClient_SendEventAsync I should see a message timeout in 1 second, correct? What I see is message stays pending forever.

Steps:

1. Add rule to block outbound amqps traffic
2. Add message with IoTHubClient_SendEventAsync
3. Never times out?

Also I observe IoTHubClient_SendEventAsync blocks forever (or longer than I was willing to wait) if you do the following.

1. Add rule to block outbound amqps traffic
2. Restart test program which does IoTHubClient_SendEventAsync
3. IoTHubClient_SendEventAsync never returns

Also I observe same/similar behavior with IoTHubClient_GetSendStatus

I am testing from the Python bindings, but issues should still exists in C. Except IoTHubClient_GetSendStatus behavior is worse in Python because it probably is not releasing the interpreter lock.

**Comment by ewertons** [comment]
Hi @jamescmaki ,

have you tried setting the option on the C device client?

IoTHubClient_SetOption(<client handle>, "messageTimeout", <value>)

**Comment by jamescmaki** [comment]
I am setting option messageTimeout. This is not helpful. Async calls should never block.

**Comment by ewertons** [comment]
Hi @Praburaj , were you able to use AmqpTransportSettings ? Is your issue fixed using these settings?

**Comment by mregen** [comment]
@jamescmaki Hi James, a change https://github.com/Azure/azure-c-shared-utility/commit/198d80bd4cc1bd08163a960eb316fdb3142668ae has been committed to address the hang during connect. It will be in master in the next release (May-23rd) or earlier in develop. All other issues you mention above, like messageTimeout or missing GIL release, have already been fixed in the Python binding in the latest release. 
one sidenote: in the current implementation of messageTimeout we just do a best effort approach, there is no guarantee to timeout after e.g. 1000ms, because in some situation we need to hit e.g. connect timeout or other errors before the messageTimeout can be evaluated.

**Comment by ewertons** [comment]
This issue will be closed, but please feel free to re-open it once you have chance to verify the fixes, or if you need more assistance on this subject.

Please let us know if you have any other comments, suggestions or questions.
Thanks for using the Azure IoT Hub Client SDK.
