### ISSUE TITLE
Provision Device - DeviceExplorer is mentioned as an afterthought, not one of main choices.

### ISSUE THREAD

**Issue by jtanner-msft** [Azure/azure-iot-sdks#295]
In the current documentation it does mention DeviceExplorer, but only at the end as an afterthought.  
We should clearly state that for someone getting started there are two options for provisioning new devices on an IoTHub.  Currently the docs make you think that the iothub-explorer tool is the only option, and it's only after you've read all the docs related to it that you see another possibility exists.
Maybe break it out like:
Windows:
DeviceExplorer
Other Platforms:
Iothub-explorer

Or something like the above.

**Comment by dciliske** [comment]
Amusingly, I had the opposite problem, where it appeared that the only tool available was DeviceExplorer. I was going from the C library getting started guide. What documentation were you reading?

**Comment by jtanner-msft** [comment]
I'd started on this page: https://github.com/Azure/azure-iot-sdks/tree/master/c
 and was going down the list of steps provided.  This is the page I felt leaned to heavily towards iothub-explorer:
https://github.com/Azure/azure-iot-sdks/blob/master/tools/iothub-explorer/doc/provision_device.md

**Comment by olivierbloch** [comment]
The device explorer tool runs only on Windows and as we would like to enable developers on all platforms, we recommend the use of our node based X-plat CLI tool aka iothub-explorer.
We need to do a pass to put the 2 tools at the same level as they both achieve the same tasks in their own way, and as you suggest indicate clearly what they are:
the Device Explorer tool as a UI tool for Windows and the iothub-explorer as a cross platform command line tool.

One reason why we prefer iothub-explorer to be mentioned  first is because a lot of device developers are actually not running Windows on their machines...
We'll try and make it clearer in the docs. 
Thanks for bringing this up

**Comment by dominicbetts** [comment]
Hi @olivierbloch, this should be OK to close now that all the references point to manage_iot_hub.md that describes both tools.
