### ISSUE TITLE
Client for Net microframework

### ISSUE THREAD

**Issue by josesimoes** [Azure/azure-iot-sdks#30]
I was wondering if there are any plans to release a client for NetMF?

**Comment by ppatierno** [comment]
Good question ... the same for me

**Comment by msjaosborn** [comment]
We're continuing to add support for more platforms and language bindings.  There's a [feature request](http://feedback.azure.com/forums/321918-azure-iot/suggestions/10029414-netmf-support) for NetMF on our feedback site.  Head on over and vote if you haven't already!

**Comment by josesimoes** [comment]
@msjaosborn: thanks for the prompt reply! Already voted for it. :wink: 
Is it something that you already have on the works or is this something that is still to be evaluated sometime in the future? Any chance you can share with us a timeframe?

**Comment by msjaosborn** [comment]
I think you'll see it in the next couple of months.

**Comment by josesimoes** [comment]
Truly awesome! :+1: 

(if you guys need a hand with this I'm OK with to put some hours into coding or testing, just let me know)

**Comment by msjaosborn** [comment]
Thanks!

**Comment by ppatierno** [comment]
Hi all,
I already did this kind of work with my Azure SB Lite library (https://github.com/ppatierno/azuresblite). This is a wrapper around the AMQP .Net Lite library that exposes same official Service Bus APIs SDK. As you know the Service Bus SDK doesn't work on UWP apps and .Net Micro Framework due to strict relationship with WCF.
Today if you want to access Service Bus (queue, topic/subscription and event hub) from UWP app or .Net MF app you have to use AMQP .Net Lite library (but you need to know AMQP concepts) or you can use my library (you can use same code that runs on your PC with .Net).
After IoT Hub announce, my idea was to develop an IoT Hub client for .Net Micro Framework using the same approch.

Paolo

**Comment by josesimoes** [comment]
@ppatierno: I'm aware of your SB Lite library (nice job, btw). 
I did a quick attempt to port the main classes of the IoT SDK to NetMF and had them call the AMQP .NET Lite library. Got stuck in the authentication (it keeps returning a "code 2" error when opening the link). Then I reached the guys here to decide whether to put more time digging that issue or if it would be reasonable to wait for an official library. From the above I guess I'll go with option b).

**Comment by ppatierno** [comment]
@josesimoes I don't think that the option b is the right idea. :-) You already started what I'd like to do so ... If you want I can try to help you on solving issues on porting.
What do you think ? Can you share your code ? I'm ready to help you ;-)

Paolo

**Comment by josesimoes** [comment]
Hi Paolo,

I'm good working with you on this. Please send me an email and I'll discuss how to move forward with this. My email address is in my profile. 
Cheers!

**Comment by dcristoloveanu** [comment]
Hi Jose,
If you are looking at having a .NetMF port soon for the IoTHub SDK we would obviously love to have that PR into develop. Thanks!
/Dan

**Comment by josesimoes** [comment]
Hello,

Just created PR (#38) with a .NETMF client.
Support for HTTP only at this time (I'm working on the AMQP).

(thanks to @ppatierno and @dcristoloveanu for the "encouragement" :wink: )

**Comment by tameraw** [comment]
Closing this issue since we're handling it through the PR.
