### ISSUE TITLE
Feature request: Http or AmqpWs support for service client

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdks#355]
Are there any plans of supporting other transports than Amqp for service side? My customer is would like to submit commands from existing (local) web application. Their firewall blocks port 5672...

**Comment by rajeevmv** [comment]
The C# service client already supports Amqp over WebSockets. The RegistryManager works only over Http. Support for sending C2D messages and receiving feedback over Http is in our backlog.

**Comment by tameraw** [comment]
@wmmihaa - Java & C# service clients now support AMQP_WS. Let us know if you're still blocked. Thanks.

**Comment by wmmihaa** [comment]
Still waiting for node.js I guess...

**Comment by pierreca** [comment]
@wmmihaa if you're OK to fork our repo it should be trivial to add amqp-ws support to the existing service SDK, replicating what's been done for the device SDK. the support is actually already in the common codebase, what remains to be done is create an amqp-ws transport class that inherits from the amqp one, and change the constructor to use a `wss://` URL used for the connection instead of `amqps://`. I'll happily review a pull-request for this, I'm a little backed up with other features and reducing the technical debt but I can do my best to help you get this to work.

**Comment by wmmihaa** [comment]
@pierreca I've submitted the pull request (#485). I had to make some minor changes to the _node/service/iothub.js_ and _node/service/lib/client.js_. I've tested the solution at work, but as I can't test Amqp from here, I haven't verifed that I haven't broken the original code using Amqp: 

Original (DefaultTransport = Amqp)
```
var registry = iothub.Registry.fromConnectionString(connectionString); // should still work
```
New code
```
var Transport = require('azure-iothub').AmqpWs;
var registry = iothub.Registry.fromConnectionString(connectionString,Transport ); // Tested
```
One last thing. I wasn't sure of what to set in the comment header (MIT license stuff) so I just copied from the other files

**Comment by pierreca** [comment]
Closing the issue as https://github.com/Azure/azure-iot-sdks/pull/488 was merged and the packages have now been published. v1.0.5 of our SDK includes AMQP-WS for the service. thanks a lot for your contribution!
