### ISSUE TITLE
Unable to receive events via HTTP

### ISSUE THREAD

**Issue by blindman2k** [Azure/azure-iot-sdks#363]
I am trying to get the `node/device/samples/simple_sample_device.js` example code working. It seems to send events ok but fails to receive events.

- I edit simple_sample_device.js
- I uncommend `Http` and comment `Amqp`
- I update the `connectionString` 
- I replace `Amqp` with `Http` in the `fromConnectionString` line.

I run the script and receive:
```
Client connected
Sending message: {"deviceId":"myFirstDevice","windSpeed":12.143609046004713}
send status: MessageEnqueued
Sending message: {"deviceId":"myFirstDevice","windSpeed":11.81751501467079}
send status: MessageEnqueued
Sending message: {"deviceId":"myFirstDevice","windSpeed":13.864402461796999}
send status: MessageEnqueued
Sending message: {"deviceId":"myFirstDevice","windSpeed":12.320323896594346}
send status: MessageEnqueued
```

I don't ever receive a incoming message event.

Can anyone see what I am doing wrong?

$ nodejs --version
v0.12.7

**Comment by pierreca** [comment]
how are you sending messages to the device?

**Comment by blindman2k** [comment]
I am simply running the example code. It sends messages and receives
messages.


On Wednesday, 2 March 2016, Pierre Cauchois <notifications@github.com>
wrote:

> how are you sending messages to the device?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-iot-sdks/issues/363#issuecomment-191126934>
> .
>


-- 


*Aron Steg*
*BCDE Investments, Mystic Pants, **SMS Diagnostics, SMS Broker, Zaq,
Explainers*
Mob: +61 4 3333 4444 or +1 415 728 6707 | Fax: +61 3 8677 7613

**Comment by pierreca** [comment]
Ok. It looks like you expect messages sent by the device to be received by that same device, that's not what we built with the sample. In these samples we try to separate the code that runs on the device from the code that runs on the service side, The sample you are talking about emulates only the device, but not the service side:
- it sends "device-to-cloud" messages that can be read from the service 
- It also receive "cloud-to-device" messages that the service can send to this device
- it will not receive the messages that it sends since these sent messages are intended for the service. 

if you want to see the bi-directional nature of IoT Hub you have to run both the device sample and a sample that makes use of the service: typically we recommend the device explorer or iothub explorer. see: 
- https://github.com/Azure/azure-iot-sdks/tree/master/tools/DeviceExplorer
- https://github.com/Azure/azure-iot-sdks/tree/master/tools/iothub-explorer

Please let me know if I'm misunderstanding the situation or if this makes things clearer!

**Comment by blindman2k** [comment]
That's great. I will look over the API's and see if the way I was using the
sample is the issue.
Please leave this open while I test.

Much appreciated.


*Aron Steg*
*BCDE Investments, Mystic Pants, **SMS Diagnostics, SMS Broker, Zaq,
Explainers*
Mob: +61 4 3333 4444 or +1 415 728 6707 | Fax: +61 3 8677 7613

**Comment by blindman2k** [comment]
While I think the naming of functions make this problem really likely, it seems the code itself works as designed. Thanks.
