### ISSUE TITLE
Wrong/misleading exception for RegistryManager.AddDeviceAsync failure when Device Id contains unaccepted chars

### ISSUE THREAD

**Issue by alinapopa** [Azure/azure-iot-sdks#482]
In our application we had RegistryManager.AddDeviceAsync(new Device(deviceId))
failing on the server with Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException,
exception message: "Device not registered".
The failure was caused by the presence of an unaccepted character in deviceId string.
Please throw an exception that helps the user identify the real cause of the failure.

**Comment by tameraw** [comment]
@alinapopa - Thanks for your feedback. We'll look into addressing this in a future release.
We'd also be happy to accept contributions if wish to make a Pull Request for this.

**Comment by markrad** [comment]
Hi @alinapopa,

I wrote a piece of C# that attempts to add a device with a bad name. I am seeing a System.ArgumentException being thrown with the message _"The device identifier \<my bad device id> is invalid._
Possible this has been fixed in the meantime. Could you test it again please?
_Mark Radbourne MSFT_

**Comment by alinapopa** [comment]
Yes that is correct, I have tried it and I get the same exception and message. Closing the issue.
