### ISSUE TITLE
[Question][Linux][cmake] How to add dependencies to existing CMakeLists.txt

### ISSUE THREAD

**Issue by shazz** [Azure/azure-iot-sdks#504]
Hi,

Sorry for the dumb question (new to cmake) but better than breaking the SDK organization :)

Let's assume I'd like to modify the linux `simplesample_http` example and poll real Raspberry Pi GPIO instead of simulating measures and to do that, I need to use and link the BCM2835 library (http://www.airspayce.com/mikem/bcm2835/), what should I modify in the `CMakeLists.txt` from the example to include and link (let's assume from `/usr/local/lib/libbcm2825.a` and `/usr/local/include`)  ?

Thanks !

shazz

**Comment by markrad** [comment]
Hi @shazz,
I would not recommend that you modify the CMakeLists.txt to build your version of the sample code. Each time you modified your sample you would end up waiting for the entire SDK to build again. I believe a better approach would be to build the SDK once and then set up your own build environment for the code you wish to test. Typically for quick tests I create a makefile to build my code with make. Here is a simple example of a makefile from my Ubuntu machine:
```makefile
CC = gcc

INCDIRS = \
    -I/home/markrad/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility \
    -I/home/markrad/Source/azure-iot-sdks/c/azure-c-shared-utility/inc \
    -I/home/markrad/Source/azure-iot-sdks/c/azure-c-shared-utility/c/inc \
    -I/home/markrad/Source/azure-iot-sdks/c/iothub_client/inc

CFLAGS = -std=c99

BINS = main.o

LIBDIRS = \
    -L/home/markrad/cmake/iothub_client \
    -L/home/markrad/cmake/azure-c-shared-utility/c/ \
    -L/home/markrad/cmake/azure-uamqp-c \
    -L/home/markrad/cmake/azure-umqtt-c \
    -L/home/markrad/cmake/azure-c-shared-utility

LIBS = \
    -liothub_client_amqp_transport \
    -liothub_client_http_transport \
    -luamqp \
    -lumqtt \
    -liothub_client \
    -laziotsharedutil \
    -lcurl \
    -lssl \
    -lcrypto \
    -lpthread

TARGETS = testapp

###############################################################################
	
.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
	rm -f $(TARGETS)
	rm -f $(BINS)

###############################################################################

testapp: $(BINS)
	$(CC) -o testapp $(LIBDIRS) $(BINS) $(LIBS)

###############################################################################

main.o : main.c
	$(CC) -c $(CFLAGS) $(INCDIRS) main.c

```

**Comment by shazz** [comment]
Unfortunately I'm cross-compiling for the rpi that's why reusing the SDK sample was easier (but I agree that's not the good way).

So I modified your Makefile to cross-compile but it generates pages of errors due to the serializer macros:
```
TOOLCHAIN=$(HOME)/RPiTools/tools
SYSROOT=$(TOOLCHAIN)/rootfs

CC = $(TOOLCHAIN)/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc

INCDIRS = \
	-I$(SYSROOT)/include \
	-I$(SYSROOT)/usr/local/include \
	-I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility \
	-I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc \
	-I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/c/inc \
	-I/home/shazz/Source/azure-iot-sdks/c/iothub_client/inc \
	-I/home/shazz/Source/azure-iot-sdks/c/serializer/inc

CFLAGS = -std=c99  -Wall -g -fPIC -

BINS = rpisample_http.o main.o

LIBDIRS = \
	-L/home/shazz/cmake/iothub_client \
	-L/home/shazz/cmake/azure-c-shared-utility \
	-L/home/shazz/cmake/serializer \
	-L$(SYSROOT)/usr/local/lib \
	-L$(SYSROOT)/lib

LIBS = \
    -liothub_client_http_transport \
    -lserializer \
    -liothub_client \
    -laziotsharedutil \
    -lcurl \
    -lssl \
    -lcrypto \
    -lpthread

TARGETS = testapp

###############################################################################

.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
	rm -f $(TARGETS)
	rm -f $(BINS)

###############################################################################

testapp: $(BINS)
	$(CC) -o testapp $(LIBDIRS) $(BINS) $(LIBS)

###############################################################################

main.o : main.c
	$(CC) -c $(CFLAGS) $(INCDIRS) main.c

rpisample_http.o : rpisample_http.c
	$(CC) -c $(CFLAGS) $(INCDIRS) rpisample_http.c	
	

```

ex:
```
shazz@ubuntu:~/Source/test$ make -f Makefile.rpi
/home/shazz/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc -c -std=c99  -Wall -g -fPIC - -I/home/shazz/RPiTools/tools/rootfs/include -I/home/shazz/RPiTools/tools/rootfs/usr/local/include -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/c/inc -I/home/shazz/Source/azure-iot-sdks/c/iothub_client/inc -I/home/shazz/Source/azure-iot-sdks/c/serializer/inc main.c
arm-linux-gnueabihf-gcc: error: -E or -x required when input is from standard input
In file included from /home/shazz/Source/azure-iot-sdks/c/serializer/inc/serializer.h:55:0,
                 from rpisample_http.h:11,
                 from main.c:6:
/home/shazz/Source/azure-iot-sdks/c/serializer/inc/serializer.h:369:202: warning: left-hand operand of comma expression has no effect [-Wunused-value]
     static const REFLECTED_SOMETHING C2(REFLECTED_, C1(INC(__COUNTER__))) = { REFLECTION_ACTION_TYPE,   &C2(REFLECTED_, C1(DEC(DEC(__COUNTER__)))), { {0}, {0}, {0}, {TOSTRING(name), (0 ? (uintptr_t)("", "") : argc), argv, fn, TOSTRING(modelName)}, {0}} };
                                                                                                                                                                                                          ^
/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility/macro_utils.h:5803:26: note: in definition of macro ‘EXPAND_ARGS’
 #define EXPAND_ARGS(...) __VA_ARGS__
                          ^
/home/shazz/Source/azure-iot-sdks/c/serializer/inc/serializer.h:380:41: note: in expansion of macro ‘EXPAND_ARGS’
 #define CREATE_ELEMENT(modelName, elem) EXPAND_ARGS(CREATE_SOMETHING(modelName, EXPAND_ARGS(EXPAND_##elem)))
```

So I probably forgot something that the cmake is adding while generating the Makefiles....

Any idea ?

**Comment by markrad** [comment]
Hi Shazz,Two suggestions. First you should be able to find the makefile generated by cmake in your ~/cmake directory. I looked at a couple of them. I'm not really a make expert and it would take me a significant amount of time to try and reverse engineer one of them. Second you might trying adding -cl -### to the standard build.sh run when you build the SDK. According to the documentation this will cause the tools to dump all of their command arguments (but not actually do the build). I've not tried this personally.
Mark Radbourne MSFTDate: Fri, 22 Apr 2016 10:26:34 -0700
From: notifications@github.com
To: azure-iot-sdks@noreply.github.com
CC: markrad@msn.com; comment@noreply.github.com
Subject: Re: [Azure/azure-iot-sdks] [Question][Linux][cmake] How to add dependencies to existing CMakeLists.txt (#504)

Unfortunately I'm cross-compiling for the rpi that's why reusing the SDK sample was easier (but I agree that's not the good way).


So I modified your Makefile to cross-compile but it generates pages of errors due to the serializer macros:


TOOLCHAIN=$(HOME)/RPiTools/tools
SYSROOT=$(TOOLCHAIN)/rootfs

CC = $(TOOLCHAIN)/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc

INCDIRS = \
    -I$(SYSROOT)/include \
    -I$(SYSROOT)/usr/local/include \
    -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility \
    -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc \
    -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/c/inc \
    -I/home/shazz/Source/azure-iot-sdks/c/iothub_client/inc \
    -I/home/shazz/Source/azure-iot-sdks/c/serializer/inc

CFLAGS = -std=c99  -Wall -g -fPIC -

BINS = rpisample_http.o main.o

LIBDIRS = \
    -L/home/shazz/cmake/iothub_client \
    -L/home/shazz/cmake/azure-c-shared-utility \
    -L/home/shazz/cmake/serializer \
    -L$(SYSROOT)/usr/local/lib \
    -L$(SYSROOT)/lib

LIBS = \
    -liothub_client_http_transport \
    -lserializer \
    -liothub_client \
    -laziotsharedutil \
    -lcurl \
    -lssl \
    -lcrypto \
    -lpthread

TARGETS = testapp

###############################################################################

.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
    rm -f $(TARGETS)
    rm -f $(BINS)

###############################################################################

testapp: $(BINS)
    $(CC) -o testapp $(LIBDIRS) $(BINS) $(LIBS)

###############################################################################

main.o : main.c
    $(CC) -c $(CFLAGS) $(INCDIRS) main.c

rpisample_http.o : rpisample_http.c
    $(CC) -c $(CFLAGS) $(INCDIRS) rpisample_http.c  




ex:


shazz@ubuntu:~/Source/test$ make -f Makefile.rpi
/home/shazz/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc -c -std=c99  -Wall -g -fPIC - -I/home/shazz/RPiTools/tools/rootfs/include -I/home/shazz/RPiTools/tools/rootfs/usr/local/include -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc -I/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/c/inc -I/home/shazz/Source/azure-iot-sdks/c/iothub_client/inc -I/home/shazz/Source/azure-iot-sdks/c/serializer/inc main.c
arm-linux-gnueabihf-gcc: error: -E or -x required when input is from standard input
In file included from /home/shazz/Source/azure-iot-sdks/c/serializer/inc/serializer.h:55:0,
                 from rpisample_http.h:11,
                 from main.c:6:
/home/shazz/Source/azure-iot-sdks/c/serializer/inc/serializer.h:369:202: warning: left-hand operand of comma expression has no effect [-Wunused-value]
     static const REFLECTED_SOMETHING C2(REFLECTED_, C1(INC(__COUNTER__))) = { REFLECTION_ACTION_TYPE,   &C2(REFLECTED_, C1(DEC(DEC(__COUNTER__)))), { {0}, {0}, {0}, {TOSTRING(name), (0 ? (uintptr_t)("", "") : argc), argv, fn, TOSTRING(modelName)}, {0}} };
                                                                                                                                                                                                          ^
/home/shazz/Source/azure-iot-sdks/c/azure-c-shared-utility/inc/azure_c_shared_utility/macro_utils.h:5803:26: note: in definition of macro ‘EXPAND_ARGS’
 #define EXPAND_ARGS(...) __VA_ARGS__
                          ^
/home/shazz/Source/azure-iot-sdks/c/serializer/inc/serializer.h:380:41: note: in expansion of macro ‘EXPAND_ARGS’
 #define CREATE_ELEMENT(modelName, elem) EXPAND_ARGS(CREATE_SOMETHING(modelName, EXPAND_ARGS(EXPAND_##elem)))


So I probably forgot something that the cmake is adding while generating the Makefiles....


Any idea ?


—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub

**Comment by markrad** [comment]
Hi @shazz 

Let me rewrite my comment above. I responded in email and didn't realize it would put the entire thread in making it rather difficult to read.

Two suggestions. 
First you should be able to find the makefile generated by cmake in your ~/cmake directory. I looked at a couple of them. I'm not really a make expert and it would take me a significant amount of time to try and reverse engineer one of them. 
Second you might trying adding -cl -### to the standard build.sh run when you build the SDK. According to the documentation this will cause the tools to dump all of their command arguments (but not actually do the build). I've not tried this personally but it may help decipher what cmake is adding.

_Mark Radbourne MSFT_

**Comment by shazz** [comment]
Hi Mark,
In fact you answered to a comment I deleted in the meantime.

I tweaked a little your Makefile and now it works perfectly, so it really helped. Now I do things rights and I stopped modifying the SDK examples ^^.

The only thing I did not solve yet, if I replace the absolute paths like -I/home/shazz/cmake/... by -I~/cmake to be a little bit more "portable", it doesn't work. 
Is there a way to build the SDK and then as usual "make install" (libs and includes) in something like /usr/local/lib or wherever and leave the user directory ?

**Comment by markrad** [comment]
Hi @shazz,

I would have expected the -L~/cmake... to work. What sort of error message do you see when you try that? Does it simply not find the library directories?

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @shazz,

I did some more research into the -L~/somedir issue you are seeing. Apparently makefiles do not cooperate well with the tilde shortcut. The circumvention is to use the environment variable $HOME. Modify your -I and -L lines to read:
```
-I $$HOME/somedir
-L $$HOME/somedir
```

Notice the space between the -I and the -L and its parameter.

Since your issue has been resolved, I have closed it. If you have further related problems you are welcome to reopen it.

_Mark Radbourne MSFT_
