### ISSUE TITLE
[Java Device Client][Re] AMQPS, quite long delay before detecting network disconnection

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdks#549]
Reopen issue #540 

After downloading and trying the new version 1.0.6 we experience exactly the same behaviour. 

How to reproduce and test this issue:

1) Connect to IoTHub and send a couple of messages to be sure there's an open connection
2) Disconnect internet (unplug ethernet for example)
3) Send a message
4) Wait for a really long time (> 5 minutes) until the sdk detects the disconnection and the callback is executed with ERROR state

**Comment by iluican** [comment]
Hi,

Due to an error on our side, we haven't published 1.0.6 yet, is it possible you were still using 1.0.5 without realizing?

We are working on publishing 1.0.6 again, should be done by tomorrow.

Meanwhile I will try to repro your issue using our latest code and let you know my findings.

Thank you,
Ilie.

**Comment by iluican** [comment]
I followed the steps you mentioned against the latest SDK code, and here are my findings:

- from the moment the ethernet cable is unplugged, it took the SDK ~20 seconds to figure out something went wrong. It then started attempting to reconnect to the IoTHub, while displaying a message in the console - "Lost connection to the server. Reconnection attempt x...". It kept doing that while the connection was down. As an FYI on how often we try to reconnect, we're using an exponential backoff which eventually settles to one reconnection attempt per minute.

- after some time I plugged the ethernet cable back. From the moment Windows re-established the internet connection it took the SDK 2-3 seconds to reconnect to the IoT Hub and send all the messages which were accumulating while the connection was down. It then received the acks from the server and all the callbacks were executed successfully.

It seems your scenario is a bit different, though - you'd like the callback to be executed with an ERROR state when the connection is down. This is something that the latest SDK version does not support. It will just buffer the messages until the connection is re-established and then send all of them. We have a work item in our backlog to add a message duration (timeout or expiration, if you will), so that the callback is executed with an ERROR state if the message has been in the waiting state for too long.

Please let me know if I misunderstood your situation or if you have further questions.

Thank you,
Ilie.

**Comment by pizerg** [comment]
Hi,

I believe we've been using version 1.0.6 as I can also see the messages "Lost connection to the server. Reconnection attempt x..." and built the code myself from the repo (did not use maven dependency from maven central).

Thank you for your investigation, I think you got the situation perfectly, our scenario needs immediate feedback about the message delivery as we then handle the resending of the messages ourselves, if a message cannot be delivered immediately then we save the message and try to send them later (with some additional logic involved), having no feedback until a reconnection happens could cause losing those messages if the power goes down for example.

Having that said, I think "message duration / timeout" would work on our scenario solving the issues we've been experiencing.

Thanks,

Adrián

**Comment by markrad** [comment]
Hi @pizerg,

Currently the product group are deliberating about the timeframe in which they may be able to deliver this functionality. Briefly they are considering some sort of callback when the network state changes. I can't give you any estimate of when you might see this functionality.

_Mark Radbourne MSFT_

**Comment by tameraw** [comment]
@pizerg - In the C client SDK we provide the option to set "no timeout" in which case the client will attempt to send the message, then will invoke the callback with the status right away. Currently that's not an option in the Java SDK. We're working on solution to align all c-client features with the java client while maintaining the cross platform benefit of a java SDK.

**Comment by pizerg** [comment]
@tameraw That's great news, thanks for the update!

**Comment by tameraw** [comment]
@pizerg - Addressing the original post.
We're currently working on enhancing the retry logic and connection error reporting. Through that effort, you should be able to achieve the scenario you asked for.
A link to the GitHub project is here:
https://github.com/Azure/azure-iot-sdks/projects/2
