### ISSUE TITLE
Error compiling iothub_csharp_netmf_client.sln

### ISSUE THREAD

**Issue by rtodosic** [Azure/azure-iot-sdks#553]
You can no longer compile /csharp/device/iothub_csharp_netmf_client.sln. The error is that PCLCrypto isn't found. Also PCLCrpyto isn't compatible with the .Net Micro Framework 4.3 or 4.4.  It looks like the PCL project was added for Andriod and iOS. We may need more compiler directives for NETMF. 

@iluican

**Comment by markrad** [comment]
Hi @rtodosic,

I'm taking a look at this issue. I'll update you when I know more.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @rtodosic,

Sorry for the delay.

I concur. It would seem that the build was not tested after the Android and iOS pieces were introduced. I'm discussing this with the product group.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @rtodosic 

This is being addressed.

**Comment by josesimoes** [comment]
Hi,

I've just submitted PR #738 correcting this.

As it was already pointed out, the NETMF projects simply weren't compiling because of recent changes.
There were a lot of corrections required. Some of them was to put back code that was inadvertedly removed!

If you don't mind me saying it seems that you are not showing enough love to the NETMF SDK...
Suggest that you are mode careful in the future when removing and adding code. Please make sure to open the NETMF solution and give it a try, just to check if it compiles... 😉

**Comment by markrad** [comment]
Hi @josesimoes @rtodosic 

This was fixed this week. The changes have been pushed to the develop branch. 

Yes we have likely been a little neglectful of NETMF but we will be adding build gate in the near future to prevent anybody committing code to develop that will not build in NETMF. Things should be more reliable after that.

_Mark Radbourne MSFT_
