### ISSUE TITLE
[python][Windows] python SDK build fail on windows 10

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-iot-sdks#597]
Hi guys,

I build C SDK successfully on Windows following the instructions, and then I want to build python with build.cmd, any ideas?? Thanks a lot!

python\build_all\windows>build.cmd

Build FAILED.

       "D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\iothub_client_python.sln" (default target)
        (1) ->
       "D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\client\iothub_client.vcxproj" (default tar
       get) (2) ->
       (ClCompile target) ->
         D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\packages\boost.1.60.0.0\lib\native\includ
       e\boost/python/detail/caller.hpp(55): warning C4244: 'return': conversion from 'Py_ssize_t' to 'unsigned int', p
       ossible loss of data [D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\client\iothub_client.
       vcxproj]

       "D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\iothub_client_python.sln" (default target)
        (1) ->
       "D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\client\iothub_client.vcxproj" (default tar
       get) (2) ->
       (ClCompile target) ->
         ..\..\src\iothub_client_python.cpp(10): fatal error C1083: Cannot open include file: 'azure_c_shared_utility/p
       latform.h': No such file or directory [D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\clie
       nt\iothub_client.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:40.07

**Comment by kingliantop** [comment]
Yes, I think so, here are the packages:

D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\packages>dir
 Volume in drive D is Dev
 Volume Serial Number is D2A6-C8D1

 Directory of D:\iotdemo\azure-iot-sdks\python\device\iothub_client_python\windows\packages

2016/06/01  20:23    <DIR>          .
2016/06/01  20:23    <DIR>          ..
2016/06/01  20:43    <DIR>          boost.1.60.0.0
2016/06/01  20:22    <DIR>          boost_python.1.60.0.0
2016/06/01  20:22    <DIR>          Microsoft.Azure.C.SharedUtility.1.0.8
2016/06/01  20:21    <DIR>          Microsoft.Azure.IoTHub.AmqpTransport.1.0.8
2016/06/01  20:21    <DIR>          Microsoft.Azure.IoTHub.HttpTransport.1.0.8
2016/06/01  20:21    <DIR>          Microsoft.Azure.IoTHub.IoTHubClient.1.0.8
2016/06/01  20:21    <DIR>          Microsoft.Azure.IoTHub.MqttTransport.1.0.8
2016/06/01  20:21    <DIR>          Microsoft.Azure.uamqp.1.0.8
2016/06/01  20:21    <DIR>          Microsoft.Azure.umqtt.1.0.7
               0 File(s)              0 bytes
              11 Dir(s)  73,169,539,072 bytes free

**Comment by mregen** [comment]
@kingliantop Hi, I found an issue in the project file. There is a bug in our patching code for the vc project which didn't update a ref to Azure shared utility to 1.0.8:

`python/device/iothub_client_python/windows/client/iothub_client.vcxproj
     <Import Project="..\packages\Microsoft.Azure.C.SharedUtility.1.0.7\build\native\Microsoft.Azure.C.SharedUtility.targets
`

The problem is not visible if there is still a 1.07 package installed from the previous release in your repo. 
As a workaround you could edit the line and change all references to 1.0.8. But the issue should also be addressed for the next release (end of week).

Thanks for the feedback!

**Comment by mregen** [comment]
@kingliantop the package mismatch has been resolved. All Packages are updated to 1.0.9 or 1.0.8. Just as a sidenote, in this release we just discovered a new issue building with nuget packages against 64 bit Python targets. Please use x86 / 32 bit Python targets until the issue is resolved. Sorry for the inconvenience.
