### ISSUE TITLE
Error compiling Java Device in Running tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest

### ISSUE THREAD

**Issue by 65tux** [Azure/azure-iot-sdks#607]
downloaded a fresh copy of the repository per the instructions, tried the maven install, get the following error:

-------------------------------------------------------------------------------
Test set: tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest
-------------------------------------------------------------------------------
Tests run: 34, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.109 sec <<< FAILURE! - in tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest
openTriggersProtonReactor(tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest)  Time elapsed: 0.26 sec  <<< ERROR!
mockit.internal.MissingInvocation: 
Missing 1 invocation to:
com.microsoft.azure.iothub.transport.amqps.IotHubReactor#run()
   on mock instance: com.microsoft.azure.iothub.transport.amqps.IotHubReactor@2fc1d
	at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest.openTriggersProtonReactor(AmqpsIotHubConnectionTest.java:423)
Caused by: mockit.internal.expectations.invocation.ExpectationError
	at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest.openTriggersProtonReactor(AmqpsIotHubConnectionTest.java:423)

**Comment by markrad** [comment]
I'll take a look at this.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @65tux,

I took a look at this. I followed the instructions [here](https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/java-devbox-setup.md) and then [here](https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/java-run-sample.md). I saw the same error that you encountered.
```
Tests run: 34, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.438 sec <<< FAILURE! - in tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest
openTriggersProtonReactor(tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest)  Time elapsed: 0.1 sec  <<< ERROR!
mockit.internal.MissingInvocation:
Missing 1 invocation to:
com.microsoft.azure.iothub.transport.amqps.IotHubReactor#run()
   on mock instance: com.microsoft.azure.iothub.transport.amqps.IotHubReactor@41f69e84
        at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest.openTriggersProtonReactor(AmqpsIotHubConnectionTest.java:423)
Caused by: mockit.internal.expectations.invocation.ExpectationError
        at tests.unit.com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnectionTest.openTriggersProtonReactor(AmqpsIotHubConnectionTest.java:423)
```
It appears to be an issue with the build script. If I were to guess, I would suggest that it is doing something in the wrong sequence because when I ran the build script again it was successful. I was then able to run the send-event sample without any issue.

I suggest you simply run the build again and see if this solves your problem too. In the meantime I will research the build problem.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @65tux,
The build issue has been addressed and resolved. Thank you for bringing this to our attention.
_Mark Radbourne MSFT_
