### ISSUE TITLE
C# DeviceClient.ReceiveAsync losing messages

### ISSUE THREAD

**Issue by fpagliar** [Azure/azure-iot-sdks#608]
I have a scenario in C# doing:

```
deviceClient = DeviceClient.CreateFromConnectionString(connection.GetConnectionString());
Message receivedMessage = await deviceClient.ReceiveAsync();
if(receivedMessage != null) {
       ProcessMessage(receivedMessage);
       await deviceClient.CompleteAsync(receivedMessage);
}
```

In some cases, CompleteAsync will throw an exception, so I expect the message no to be removed from the IoT queue, and be received again the next time I call to ReceiveAsync. 
Yet this is not always the case, sometimes it is sent again, sometimes it is not.

**Comment by rajeevmv** [comment]
This is expected behavior. For example, the CompleteAsync message could have reached the service which then proceeded to delete the corresponding device command. However, the device client lost communication before the service could ack the CompleteAsync message. This could manifest as a timeout message on the client.

Can you elaborate on the type of exceptions that you are seeing and their corresponding behavior - ie., does the command stay or get deleted? Could you also indicate if you are seeing predictable behavior - ie., a certain exception always deletes the message etc

**Comment by fpagliar** [comment]
The exception I was seeing is: "Token was cancelled" but I couldn't predict if the next call would have the message or not. I didn't put much time on it either, as I wasn't aware of the expected behavior.
I understand now that this is a case of the Two General's Problem and that's why the documentation states that the design should be to have idempotent messages.

Thanks!
