### ISSUE TITLE
can not read property sendframe of undefined

### ISSUE THREAD

**Issue by hamzaanjum** [Azure/azure-iot-sdks#609]
I am using the Azure IoT NodeJS Sdk, and the receiver is crashing my application while attempting to reattach. It crashes after about 2 days of running. I have even added manual refreshing of the amqp client every 10 minutes and disconnecting the old one, and now it managed to run for about 5 days, but then crashed with the same error.

<img width="601" alt="error screenshot blurred" src="https://cloud.githubusercontent.com/assets/9820827/15802731/29c2b534-2ad6-11e6-8bb9-2b6089657f37.png">

**Comment by hamzaanjum** [comment]
I am using the code from this tutorials

https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-getstarted/#receive-device-to-cloud-messages

**Comment by pierreca** [comment]
It would help a lot to see a little more of your code. is that error happening on the device side, or on the cloud side trying to receive messages sent by the device?

ping @noodlefrenzy since this looks (at least on the surface) related to node-amqp10

**Comment by hamzaanjum** [comment]
The cloud side. The code is the same, that is used in the article that I already mentioned

https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-getstarted/#receive-device-to-cloud-messages

**Comment by pierreca** [comment]
Alright, so just to triple-confirm, the code that is supposed to go in the `ReadDeviceToCloudMessages.js` file right?

In the article you mention, our SDK is used only to create the device. Listening to the messages is done using the amqp10 library directly, which lives in another repository and is not maintained directly by the team behind the Azure IoT SDKs (although we do work with the maintainers of amqp10 on a regular basis and even contribute): https://github.com/noodlefrenzy/node-amqp10/

I will reach out and try to get their attention, in the meantime I can suggest a couple of things: 
1. can you update your answer or add a new comment with the version of the amqp10 library that you are using?
2. ping @dominicbetts, the author of the article so that he's aware of the issue too.
3. There is a Node.js event-hubs SDK here: https://github.com/azure/azure-event-hubs/ that is published on NPM here: https://www.npmjs.com/package/azure-event-hubs. Not sure it would help since it's also based on amqp10 but it's worth a try and should simplify your code a little bit anyway.

**Comment by pierreca** [comment]
@hamzaanjum can you update us based on the suggestions I made in my last comment?

**Comment by pierreca** [comment]
was also opened here: https://github.com/noodlefrenzy/node-amqp10/issues/237
Since it looks like a problem with the amqp10 library I'm closing it here, feel free to reopen if useful, I have subscribed to notifications on the amqp10 page so if anything happens there and requires action on our side I'll take care of it. Thanks!

**Comment by hamzaanjum** [comment]
Apologies for replying too late, coz I moved to that other link that you mentioned earlier, the version I am using is 3.1.4
I am running it in debug mode right now, and its running perfectly fine from the last 2 weeks.
And thanks, I'll try that event-hub-sdk too if I still run into any problems.

**Comment by dominicbetts** [comment]
FYI, we've recently updated the tutorial code referred to at the start of this thread to use the Node.js event-hubs SDK (https://github.com/azure/azure-event-hubs/) that is published on NPM here: https://www.npmjs.com/package/azure-event-hubs. 
As pointed out by @pierreca, it does simplify the code!

**Comment by hamzaanjum** [comment]
Yeah, I have gone through the new tutorial @dominicbetts. It shows how to receive Device to Cloud messages using the event-hubs SDK using much more simpler and cleaner code. Is it possible to send Cloud to Device messages with this same event-hub SDK? The tutorial still uses the iot-sdk to send C2D messages in the **Create a simulated device app** section.

**Comment by dominicbetts** [comment]
Hi @hamzaanjum To send device-to-cloud messages, the simulated device app uses the azure-iot-device package, you cannot use the event-hub SDK for this. In the context of IoT Hub, the only place you can use the event-hub SDK is reading cloud-to-device messages from the Event Hubs-compatible endpoint.

**Comment by hamzaanjum** [comment]
got it, thanks @dominicbetts

**Comment by hamzaanjum** [comment]
@pierreca where can I send you the buggy part of the logs? I have got it crashed with debugging enabled (using environment variable), now going to shift to the azure-event-hubs SDK.

**Comment by pierreca** [comment]
@hamzaanjum I would post it there: https://github.com/noodlefrenzy/node-amqp10/issues/237
