### ISSUE TITLE
Vague instructions

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#61]
In the section:
*Get device connection string or configuration data*

*•Use the mouse right click for context menu for the selected device. The menu has the following option*

So do I get the connection string or the configuration data? Which? The menu does have the following options but the documentation doesn't specify which option I should use. Also it should read __*options*__

**Comment by andrew-buckley** [comment]
Hi @markrad, thank you for opening this issue. I believe the document you are referring to is the "How to use Device Explorer for IoT Hub devices". This doc is intended to simply show all of the available options in the Device Explorer tool how to use the tool rather than outlining a particular workflow. Along those lines, the section you are referring to is just meant to show where/how to obtain device data and connection strings when you need them. 

The option you should use depends on the scenario. I would say that normally you will be getting the connection string from this options box. The docs for using the device SDK for each language will tell you when to obtain the connection string from the device explorer and where to put it. 

Although, yes you are correct, it should read **_options_**. I will make this change.

Hope this helps!

**Comment by andrew-buckley** [comment]
Hi @markrad, I've made the change to fix that typo. Thanks!
