### ISSUE TITLE
[DM][Linux][C] behaviour on shuttdown

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#629]
Hi,

When using the ./iotdm_simple_sample -cs "mystring" -to 2, an error is displayed right before the end of the sample:
`Error: Time:Tue Jun 14 16:52:30 2016 File:/home/lmussier/workspace/Agents/iothub/agent/external/azure-iot-sdks/c/iotdm_client/src/iotdm_client.c Func:IoTHubClient_DM_DoWork Line:520 Uninitialized lwm2m session`

Is this the correct behaviour, or a bug ?
In my code I have to check if IoTHubClient_DM_Start return IOTHUB_CLIENT_ERROR upon normal close route ?

**Comment by BertKleewein** [comment]
This is expected, but there are 2 minor bugs here:
1) The Error message should not be displayed after calling IoTHubClient_DM_Close
2) IoTHubClient_DM_Start should not return IOTHUB_CLIENT_ERROR after the user calls IoTHubClient_DM_Close.  

For now, you can safely ignore those errors.  I will be creating a bug so that we can fix this.  Would you like to be notified of it's resolution?

**Comment by lmussier** [comment]
Yes ping me when it is resolved, thanks.

**Comment by BertKleewein** [comment]
Thank you for reporting this issue. I discussed this issue with my team. We will address this problem on the next major update to the device SDK. For now, you should ignore the error message and the return code.  
Thanks
