### ISSUE TITLE
Update Export/Import registry methods to protected

### ISSUE THREAD

**Issue by krish-gh** [Azure/azure-iot-sdks#682]
Commit 93456477 Update Export/Import registry methods to protected

Current access specifier of internal abstract makes this class impossible to mock/stub/fake which is preventing to write unit test for the class which is using RegistryManager.

**Comment by rajeevmv** [comment]
These methods are obsolete. We should just go ahead and remove them instead of marking them "protected".

**Comment by tameraw** [comment]
@krish-gh - Closing. If still having issues, please reactivate or file new issue. Thanks.

**Comment by geekcubed** [comment]
Just ran into this issue myself so resurrecting in hope of a fix.  The `internal abstract` modifiers on the import / export methods of `Microsoft.Azure.Devices.RegistryManager` prevent it from being mocked as part of a test suite.  

In order to test my application logic I'm looking to implement a basic version of the RegistryManager that just supports storing it's data in memory, without the need for a connection to Azure.  I'm working around the issue by hiding the RegistryManager behind an interface which exposes the methods I need, but this definitely counts as a code-smell in my book.

If the methods are obsolete then they should be marked as such and changed to protected - this has already been employed for methods such as `AddDevicesAsync`.   Also it may be worthwhile extracting a genuine Interface for the RegistryManager to aid it's use with Dependency Injection.
