### ISSUE TITLE
Properties set using Java SDK are not present on an EventData object

### ISSUE THREAD

**Issue by vslepakov** [Azure/azure-iot-sdks#687]
We use this code to set a couple of application properties using the Java SDK:
```
Message outgoing = new Message(...);
myObject.getProperties().forEach((key, value) -> {
     outgoing.setProperty(key, value);
}); 
```
EventData instances read from the EventHub compatible endpoint (of IoT Hub) do not contain those properties.
Is there another way to set properties? They are needed among other things for payload description.

**Comment by zolvarga** [comment]
Hi vslepakov,

There is no other way to set the Message properties, but it would not be necessary because this way you can set it successfully. Please take a look at the SendReceive (..java\device\samples\send-receive-sample\src\main\java\samples\com\microsoft\azure\iothub\SendReceive.java) sample in the DeviceClient code.
At line 225 there is a sample to set custom properties. Those message properties will show up in DeviceExplorer (a ServiceClient) properly. Please try the sample out and let us know what is the difference between your and our scenario.

Thanks,
Zoltan

**Comment by vslepakov** [comment]
Hi Zoltan,

thank you for pointing me in the right direction. 
It appears that we used some older/incorrect version of the sdk that we got through maven.
We resolved the issue by upgrading the sdk. Now it works as expected.

Thanks again
Regards
Vitaliy
