### ISSUE TITLE
New issue: Captilazed Device Name fails

### ISSUE THREAD

**Issue by irjudson** [Azure/azure-iot-sdks#708]
iothub-explorer create Thingy --connection-string fails, when
iothub-explorer create thingy  --connection-string succeeds.

**Comment by pierreca** [comment]
Hi @irjudson 

Can you paste the whole trace of the problem? especially the error? I have not been able to reproduce the issue, and have been able to create devices with all sorts of casing without problem. 

Thanks!

**Comment by stefangordon** [comment]
Also confirmed there is no problem here.   Presumably the device already existed.  Due to case sensitivity it worked with a different cast.  

The message returned on a conflict is a bit of a bug though, and probably increases user confusion:
![image](https://cloud.githubusercontent.com/assets/4087345/16883185/8cb7353c-4a77-11e6-86ac-4cb3a38b0936.png)
which should presumably be `conflict`

**Comment by pierreca** [comment]
@stefangordon yes, this is a known issue that will be fixed with the next release.

**Comment by pierreca** [comment]
Closing due to lack of information and unable to reproduce the error. Feel free to reopen if you run into this again.
