### ISSUE TITLE
[C][Linux] Build failed with --use-websockets

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks#737]
Hi, 

A recent push on develop make the build to fail.

./build.sh --use-websockets --skip-unittests

```
[ 23%] Building C object azure-uamqp-c/libwebsockets/CMakeFiles/websockets.dir/lib/base64-decode.c.o
In file included from /home/jenkins/workspace/Official_IoT_Hub_SDK/Official_IoT_Hub_SDK_amd64/c/azure-uamqp-c/libwebsockets/lib/private-libwebsockets.h:30:0,
                 from /home/jenkins/workspace/Official_IoT_Hub_SDK/Official_IoT_Hub_SDK_amd64/c/azure-uamqp-c/libwebsockets/lib/base64-decode.c:44:
/usr/include/stdlib.h:466:29: error: expected ‘)’ before ‘__size’
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
                             ^
/usr/include/stdlib.h:480:23: error: expected identifier or ‘(’ before ‘void’
 extern void *realloc (void *__ptr, size_t __size)
```

Revision b558fea7c2ecccc3caf226fe779532274cedf3ad is the first one to fail, a24bd7c35afe6cd63e790a3e989fcad044402880 is ok.

**Comment by anporumb** [comment]
Very interesting. I am not seeing this on any of the Linux flavors we build in our gate.

What's your environment so I can reproduce this?

Best Regards,
Andrei Porumb

**Comment by lmussier** [comment]
Ubuntu 16.04 LTS 32bits (seen also with a 14.04 LTS)
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1)

It is on an incremental workspace, I'll try with a workspace wipeout.

**Comment by anporumb** [comment]
Linux version         |  gcc version                                        | libc version                  | result 
----------------------|-----------------------------------------------------|-------------------------------|--------
Ubuntu 14.04.4 LTS    | gcc (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3             | Ubuntu EGLIBC 2.19-0ubuntu6.9 | BAD
Ubuntu 15.10          | gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010         | Ubuntu GLIBC 2.21-0ubuntu4.3  | BAD
Ubuntu 16.04.1 LTS    | gcc (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609  | Ubuntu GLIBC 2.23-0ubuntu3    | GOOD

It so appears that my checkin with SHA f2e17eceed955eed4d5cdab4c3a5581afb549fa4 in https://github.com/Azure/azure-uamqp-c is the breaking point.

This is most interesting because the error appears in libwebsockets which I have not touched. More investigation is needed.

**Comment by anporumb** [comment]
It seems that adding -Werror to the list of C_FLAGS in CMakeLists.txt triggers the error in libwebsockets. (removing it by hand made the build successful).

Next step is to craft special C_FLAGS  for libwebsockets.

**Comment by anporumb** [comment]
Code has been crafted and checked in. Would you please let me know how it functions for you?

Soon we shall have a check in that fixes behavior for Windows as well.

Best Regards,
Andrei Porumb

**Comment by lmussier** [comment]
@anporumb :+1: 
Thanks for clearing that so rapidly.
