### ISSUE TITLE
DeviceClient is not mockable

### ISSUE THREAD

**Issue by moswald** [Azure/azure-iot-sdks#745]
Since `DeviceClient` doesn't implement an interface and doesn't have any virtual methods, it's not testable by the end user. We are working around this by writing a wrapper class that just forwards methods to the "real" `DeviceClient`, but it would be preferable if we could just mock the class directly.

**Comment by markrad** [comment]
Hi @moswald,

Can you provide me with a little more information about your issue please? 

What language are you using, C#, Java, Node.js, etc?

Thank you.

_Mark Radbourne MSFT_

**Comment by moswald** [comment]
My apologies, I should have mentioned this. This is C#.

**Comment by markrad** [comment]
Hi @moswald,

If I understand correctly then, you would have liked to see the DeviceClient inheriting from something like IDeviceClient so that you could provide a mock version of the class for testing purposes. Alternatively, if the methods were virtual, then you could have overridden them for the same end.

I'll raise this issue and get back to you.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @moswald,

I have discussed this issue with the product group. They have had other similar requests and they will consider adding it to the backlog. However, this enhancement is not going to be addressed anytime soon.

Thank you for raising the issue. I am going to keep this open in order to track your request.

_Mark Radbourne MSFT_

**Comment by tameraw** [comment]
Unfortunately, this is currently not a priority in our backlog. 
But if this is still a priority on your end, the Microsoft Customer Support team will try and help out on a best effort basis. To engage Microsoft support, you can create a support ticket directly from the [Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade).
