### ISSUE TITLE
cpp wrapper

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#751]
The python SDK utilises boost::python to create. By doing so, we are basically creating a c++ wrapper there for the iothub_client c API. 

Would it be possible to expose this wrapper in the iothub_client c package?

And then reused that client when generating the python client? This would increase the usage in c++ while still enabling python development.

I am happy to have a go at it, but just wondering if anyone wiser and more experienced than I could see limitations of this sharing. Or if having the c++ wrapper api in the c project would be a bad thing?

**Comment by tameraw** [comment]
@damienpontifex - Thanks for your proposal.
We would definitely be interested in your contribution of a C++ wrapper. We did have a discussion internally about providing such wrapper but effort to do this was not prioritized.

A few notes to point out in order to make this an efficient PR when you're ready to contribute it:
- Code organization: Let's have this under the following path of the repo "\cpp\device\iothub_client\". There you can follow the same folder structure as in the c client.
- Start with the wrapper for the iothub_client lib.
- Please provide specs and unit tests where you introduce more than a thin one-to-one mapping. As a reference: 
spec: [https://github.com/Azure/azure-iot-sdks/tree/master/c/iothub_client/devdoc](url)
unit tests: [https://github.com/Azure/azure-iot-sdks/tree/master/c/iothub_client/tests/iothubclient_unittests](url)

**Comment by damienpontifex** [comment]
@tameraw another question on the cpp file layout:
Would you prefer a src+inc structure or a header only implementation and link against the c library?

Started with the src+inc as it follows the other styles, but if users wanted to use the cpp wrapper and link against the c library, a header only implementation could be easier.

Thoughts?

**Comment by tameraw** [comment]
@damienpontifex - Please see feedback in the PR #823.

**Comment by tameraw** [comment]
@damienpontifex - Closing this and we can manage communication in the PR #823. Regards.
