### ISSUE TITLE
Xcode how to use azure-iot-sdks

### ISSUE THREAD

**Issue by yan2750** [Azure/azure-iot-sdks#771]
Hi Dev:
I have two questions.
1)Mac OS how to build azure-mqtt.
2)Xcode how to use  azure-ion-sdks.

My English is not very good,Vexed！   
                                                               thanks！

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Hi @yan2750 
Thanks for your patience ! I had chance to investigate this issue is some detail. There are number of scenarios here. It depends which option (programming language) you want to choose. There are number of programming language options here listed under
https://github.com/Azure/azure-iot-sdks and each would involve its own development and run setup.
For example, node.js would involve installing a node js package. Build requirements are listed for each option.

It also depends if you have a cross-platform scenario. For example if you want to simply build app for iPhone (iOS device), then you can simply use the Xamarin option using C# sample that builds using Xamarin cross-platform software located at 
`azure-iot-master\csharp\device\samples\DeviceClientSampleiOS`. This **C#** sample supports MQTT transport protocol option. 

I assume you are actually looking for building a Azure **C** MQTT library (azure-mqtt) https://github.com/Azure/azure-umqtt-c on Mac OS and run the application using that library on Mac OS itself. Currently tested development platforms are Windows and Linux as listed in the documentation and some cross-platform scenarios. Below link has more details
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations/

To make it build under Mac OS you will have to setup the build scripts yourself.
Azure IoT SDK C library design is structured to use **CMake** tool which simplifies building by creating native makefile and solution files which can then directly be used by compiler and linker of your choice. You will also have to set the compiler and linker you want to use for your setup. Look at `azure-iot-master\c\build_all `folder for reference. There you have folders for various platforms and there you have setup and build files. You will have to create one for Mac OS and setup your build configuration. Compiler that you choose has to be C99 compatible. If you don't want to use CMake tool, then you will have to start porting by manually adding the C files in the solution of IDE of your choice and use the compiler and linker that comes with IDE. Please note that Azure C MQTT has dependence on Azure Shared Utility (azure-c-shared-utility) https://github.com/Azure/azure-c-shared-utility . You will have to build both for linking it to your application to use MQTT protocol. Again this something you will have to do if you want to directly deal with building Azure IoT SDK C client libraries.

**Comment by anhashia** [comment]
Hi @yan2750 
It is work in progress. Some changes for making this work are already in develop branch of  azure-c-shared-utility. Check `build.sh `under https://github.com/Azure/azure-c-shared-utility/tree/develop/build_all/linux

**Comment by anhashia** [comment]
Hi @yan2750 
You also have option to using node.js on Mac OS X in case you want to use JavaScript. 
#775

**Comment by anhashia** [comment]
Closing. Please re-activate if you have any further questions on this. Thanks !
