### ISSUE TITLE
[Python] Build call 'make iothub_client_python' rather than make

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-iot-sdks#786]
With the python/linux/build_all/build.sh script, it passes through to the c targets build script and by default will do a standard `make`. 

Could this be improved to call `make iothub_client_python`? This is really the primary target that is needed in this case. Doing this manually, by going into c/cmake/iotsdk_linux and calling this, I haven't needed to create the swap file on the Raspberry Pi and the compilation time is significantly better.

**Comment by tameraw** [comment]
@damienpontifex - Thanks for filing this issue. We'll look at your suggestion.

**Comment by tameraw** [comment]
@damienpontifex - If you care to contribute this, we'd happily review the PR. Thanks.

**Comment by tameraw** [comment]
@damienpontifex - Currently this is not high in the backlog so it’s unrealistic for us to say we’re going to solve this in the near future; therefore the issue will be closed as “won’t fix” in order to not create any expectations. This being said, we’re always happy to review pull-requests if you decide to make a contribution addressing this.
