### ISSUE TITLE
InternalServerError: AMQP Transport: Could not send message

### ISSUE THREAD

**Issue by Jvaeyhcd** [Azure/azure-iot-sdks#797]
```
var connectionString = 'HostName='+hostName+';SharedAccessKeyName='+sharedAccessKeyName+';SharedAccessKey='+sharedAccessKey;

    var serviceClient = Client.fromConnectionString(connectionString);

    serviceClient.open(function (err) {
        if (err) {
            console.error('Could not connect: ' + err.message);
            var status = new Status(err.message, 300);
            routerRes.send(JSON.stringify({status: status}));
        } else {
            console.log('Service client connected');
            serviceClient.getFeedbackReceiver(receiveFeedback);

            var buffer = new Buffer(common.formatBuffer(deviceNumber, msgId, data));

            var check = common.checkBufferData(buffer.toByteArray());
            if (check) {
                var message = new Message(buffer);
                message.ack = 'full';
                message.messageId = msgId;
                console.log('Sending message: ' + (new Buffer(message.getData())).toByteArray());
                serviceClient.send(deviceNumber, message, printResultFor('send', routerRes));
            } else {
                var status = new Status('报文格式错误', 300);
                routerRes.send(JSON.stringify({status: status}));
            }


        }
    });
```

i send a message to device but `InternalServerError: AMQP Transport: Could not send message`

**Comment by pierreca** [comment]
@Jvaeyhcd 
Forgive me if I'm asking the obvious but it's not in the code: are `deviceNumber` and `printResultFor` defined and initialized?

Also, there should be more info to debug the issue in the error object itself (that you can intercept in `printResultFor`), especially in the `err.amqpError` property. can you stringify those objects and paste them here?

Thanks!

**Comment by tameraw** [comment]
@Jvaeyhcd - Let us know if still having issues. Thanks.

**Comment by Jvaeyhcd** [comment]
@pierreca When i debug，i found the `err. amqpError ` show like this:
![image](https://cloud.githubusercontent.com/assets/6993775/18665291/179fb866-7f59-11e6-8d83-ed1842e99d03.png)
what‘s it mean？

**Comment by pierreca** [comment]
Hi @Jvaeyhcd 

The maximum number of command messages (service -> device) that can be stored in a device queue  is 50. I suppose what happens is that you are queueing more messages than what your device can process so the queue fills up.

In order to avoid that, on the device side, you should acknowledge each message you receive as soon as possible by either completing, or rejecting it. This will remove it from the queue, and allow you to send more messages. The goal is to keep the number of messages waiting to be acknowledged by the device under 50 at all times.

hope that helps!

**Comment by Jvaeyhcd** [comment]
@pierreca Thank you very much,i will have a try.
