### ISSUE TITLE
How to disable certificate validation in C library? 

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-iot-sdks#826]
Hello,
        Please suggest me how can I disable certificate validation? We need a custom certificate validation so we want to disable default certificate validation because we want to exclude start and end date certificate validations. It will be great if someone suggest me any switch or flags available to disable. If there is no switch, please suggest me the file that do the certificate validation in C library.

**Comment by tameraw** [comment]
@rajvael - There is currently no switch to disable certificate validation in the SDK.

However we do provide the option to pass your cert using the "TrustedCerts" via the SetOption API.
See the sample: [https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c](url)

The option is available on Linux & MBED. It's also available on Windows but only when using AMQP over websockets.
Regards.

**Comment by rajvael** [comment]
The reason behind this i want to avoid the below error when I run the iothub sample amqp over websocket. Below is the output I am getting after run the program. How the certificate validation failing if I am not enabling it. 

Starting the IoTHub client sample AMQP over WebSockets...
Info: IoT Hub SDK for C, version 1.0.14
IoTHubClient_SetMessageCallback...successful.
[1474350084:7637] NOTICE: Initial logging level 7
[1474350084:7685] NOTICE: Libwebsockets version: 1.6.0 f1cf5be
[1474350084:7701] NOTICE: IPV6 not compiled in
[1474350084:7774] NOTICE: libev support not compiled in
[1474350084:7812] NOTICE:  ctx mem: 16916 bytes
[1474350084:8280] NOTICE:  canonical_hostname = localhost
[1474350084:8377] NOTICE:  per-conn mem: 160 + 2126 headers + protocol rx buf
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application. 
**[1474350086:3134] ERR: server's cert didn't look good, X509_V_ERR = 20: error:00000014:lib(0):func(0):SSL lib**
Error: Time:Tue Sep 20 05:41:55 2016 File:/home/avenger/azure-iot-sdk/azure-iot-sdk-2016-08-26/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1933 AMQP transport authentication timed out.
[1474350115:0093] NOTICE: lws_context_destroy
[1474350115:0332] NOTICE: Initial logging level 7
[1474350115:0404] NOTICE: Libwebsockets version: 1.6.0 f1cf5be
[1474350115:0492] NOTICE: IPV6 not compiled in
[1474350115:0496] NOTICE: libev support not compiled in
[1474350115:0514] NOTICE:  ctx mem: 16916 bytes
[1474350115:0574] NOTICE:  canonical_hostname = localhost
[1474350115:0581] NOTICE:  per-conn mem: 160 + 2126 headers + protocol rx buf
**[1474350116:2936] ERR: server's cert didn't look good, X509_V_ERR = 20: error:00000014:lib(0):func(0):SSL lib**

[1474350118:8769] NOTICE: lws_context_destroy
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

**Comment by tameraw** [comment]
@rajvael 
1) Which platform are you running when encountering this issue?
2) Which version of the SDK are you using?

Thanks.

**Comment by rajvael** [comment]
Branch : 2016-08-26 release
Code is compiled  in **Linux lcbs-dev-vm 3.19.0-68-generic #76~14.04.1-Ubuntu SMP x86_64 GNU/Linux** using cross compiler
Running Linux: **Linux 3.14.39ltsi-WR7.0.0.9_standard #4 SMP PREEMPT armv7l GNU/Linux**

**Comment by rajvael** [comment]
@tameraw 
Please update me if you have any idea why it is happening?

**Comment by tameraw** [comment]
@rajvael - Have you tried this against the latest in develop?

**Comment by tameraw** [comment]
@rajvael - Please let us know if you still have any issues. Regards.

**Comment by rajvael** [comment]
I am facing this issue ::

Build branch: https://github.com/Azure/azure-iot-sdks/tree/2016-10-14 

Starting the IoTHub client sample AMQP over WebSockets...
Info: IoT Hub SDK for C, version 1.0.17
IoTHubClient_SetMessageCallback...successful.
[18007:0843] NOTICE: Initial logging level 7
[18007:0946] NOTICE: Libwebsockets version: 1.6.0 f1cf5be
[18007:1017] NOTICE: IPV6 not compiled in
[18007:1022] NOTICE: libev support not compiled in
[18007:1033] NOTICE:  ctx mem: 16916 bytes
[18007:1068] NOTICE:  canonical_hostname = localhost
[18007:1193] NOTICE:  per-conn mem: 160 + 2126 headers + protocol rx buf
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application. 
[**18008:3335] ERR: server's cert didn't look good, X509_V_ERR = 9: error:00000009:lib(0):func(0):PEM lib**

Because I am facing this issue, my device date is not correct when it boot at first time. It was some time like 1970 Jan 01. We don't have separate time sever to correct it. This is failing because of start date or end date of the certificate is not matching with device date. I have corrected the device date to current date and it was working fine. For this reason I want to disable the certificate checks. I can do the certificate validation myself if it is required. I want to know where you put the code to validate certificate so that I can disable the certificate validation. Also I want to know is there a any flag I can use the simply disable the validation. I have removed the "TrustedCerts" option in the sample code but still it doing the validation. Please check and let me know.

**Comment by olivierbloch** [comment]
Hi @rajvael
We want to ensure connection between devices and IoT Hub is secured and definitively DON'T recommend doing this.
Have you considered pinging a NTP server to adjust the device's time before connecting to IoTHub? We are doing this in our samples for microcontroller devices that don't have an RTC.

**Comment by rajvael** [comment]
Hi @olivierbloch 

Its not just one device we can sync with NTP server. In production, there are many devices connect and send/receive message from Cloud and my company wont allow our devices to connect to NTP server running by free or third party. Actually I am already doing all the certificate validations manually before connect to the cloud. We want to disable the default certificate validation or we want custom certificate validation so that we can enable or disable some of the validation.

**Comment by dcristoloveanu** [comment]
@rajvael 

We definitely DON'T recommend disabling certificate validation like Olivier mentioned.
Here is how you should be able do it anyways if needed for development or if you know exactly what your case is.

Option 1:
- Look in wsio.c for the call to lws_client_connect (in the function wsio_open),
- Instead of passing the wsio_instance->use_ssl as argument, pass the value 2.

Option 2:
- We use libwebsockets for the websockets implementation (I see that you are running the WS code). The part of the code where you should look is wsio.c.
- The certificate load happens in the on_ws_callback function, see the case for LWS_CALLBACK_OPENSSL_LOAD_EXTRA_CLIENT_VERIFY_CERTS. The user argument contains the OpenSSL SSL_CTX *).
- You can call SSL_CTX_set_verify(user, SSL_VERIFY_NONE, NULL); to tell OpenSSL to not verify the certificate at all.

As a note for a non websocket connection you would need to do something different depending on what TLS adapter you use.

Let us know if this works for you.

Also, I am not sure I understood this statement: " Actually I am already doing all the certificate validations manually before connect to the cloud. "
When using TLS, the certificate is typically sent by the server to the client, the client then checks the validity of the cert information that was just sent by the server.
Thus, I do not think you can validate the server cert upfront before connecting, so I have probably missed something here.

Let us know what your case is as we would like to help you the best way we can secure your connection to the cloud and avoid any attacks on your system.

Thanks,
/Dan

**Comment by rajvael** [comment]
@dcristoloveanu  
I am doing certificate validation using openssl library before instantiate IOT hub library. The certificate validation that I am doing is custom validation I can easily disable or enable just setting some flags.

I need a help because most of the IoT device doesn't have RTC in it. What is your suggestion for handling those device connect to IoT hub? I knew we can connect anyone of the NTP server but the there is no guarantee in availability of those NTP servers. We cannot take any risk in connecting our device to those NTP servers. Or we have to endup in pay some vendors to make the NTP servers available all the time. 

Please suggest your thoughts around this problem. Do you know anyone has handled this issue in better way? 

Thanks
-Raj

**Comment by dcristoloveanu** [comment]
@rajvael 
AFAIK the only options are:
a) Keep track of time so that you are able to properly validate the cert information that is coming from the server on the wire. Also having the time allows you to generate tokens (SAS tokens in the case of IoTHub) with a limited validity in time.
To keep track of time there are usually 2 approaches that are used:
- get the time from an NTP.
- store the time and use a battery to power special circuitry/storage to keep that time (like it is done in PCs for example).
In many small devices the battery and extra HW is overshoot and extra cost and probably it is out of the question for you too.
If the NTP is not reliable there is not much you can do.

b) Do not keep track of time and validate as much as you can from the certificate you receive from the server (i.e. domain, title, etc, but not the expiry time).

Suggestion:
What I would suggest is putting in the NTP code and do a best effort to use it.

That means that if NTP is done or not available you can proceed to do the validation as if your device does not have time and essentially disable the validation in the client. Also please note that without a time you would have to specify a very long lifetime for the tokens that are generated by the SDK to authenticate with the IoTHub service (you would probably need to essentially default to a hardcoded time if you cannot reach the NTP and set the SAS token expiry time to be in the range of hundred years maybe - something very big, so that they are not seen as expired).
Again, I have to say we do not recommend that and ideal would be to rely on the NTP. But this obviously is something you have to decide on based on how sensitive the data that you are sending is and many other factors.

If your device did reach an NTP then best would be to use it.

Having this mixed approach will mean writing more code and doing more testing but it would reduce man in the middle attack risk.

I hope this helps.
/Dan

**Comment by tameraw** [comment]
@rajvael - After the latest update from @dcristoloveanu please let us know if you have more inquiries.

**Comment by rajvael** [comment]
Thanks. I can able to disable to certifocate using SSL_CTX_set_verify(user, SSL_VERIFY_NONE, NULL);
