### ISSUE TITLE
Iothub Sending and Receiving Messages C2D and D2C 

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#859]
i am using this for sending and receiving message
https://github.com/Azure/azure-iot-sdks/blob/master/java/device/samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/iothub/SendReceive.java
using this i am able to send while doing that i am getting a iothubstatuscode of OK_EMPTY
while receiving in the setMessageCallBack it is checking com.microsoft.azure.iothub.transport.https.HttpsIotHubConnection public Message receiveMessage()
Here it is checking messageStatus == IotHubStatusCode.OK but when i send i am getting status code OK_EMPTY so that i am not able to receive the message whatever i send .This is the main issue..

**Comment by enuysa-msft** [comment]
Hi @mupparajuvamsi,

https://github.com/Azure/azure-iot-sdks/blob/master/java/device/samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/iothub/SendReceive.java file sends messages from **Device to Cloud** and receives messages from **Cloud to Device**. 
So when you are sending messages from Device to Cloud it is normal that you are receiving feedback   with iothubstatuscode of OK_EMPTY. because it is just informing that your message is received by IoTHub without message body.

if you want to send message from **Cloud to Device** you need to use the code in https://github.com/Azure/azure-iot-sdks/blob/d5435b940253fc90cfd38ac3ab33b63300a4942c/java/service/samples/service-client-sample/src/main/java/samples/com/microsoft/azure/iot/service/sdk/ServiceClientSample.java
So then your messageStatus will be IotHubStatusCode.OK  and you will be able to receive the message in https://github.com/Azure/azure-iot-sdks/blob/master/java/device/samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/iothub/SendReceive.java

**Comment by enuysa-msft** [comment]
Closing. Please re-activate if you still are having issues. Thanks !

@tameraw Could you please close this?
