### ISSUE TITLE
[Linux][C] IoT Hub Client AMQP Memory Leak

### ISSUE THREAD

**Issue by spr-lfeliu** [Azure/azure-iot-sdks#874]
We are using the IoT Hub Client (Linux C SDK) with AMQP.

On one environment, we inadvertently added an http port number to the hostname in the connection string.

For the code specified below, we observed the following:

`while ((IoTHubClient_LL_GetSendStatus(iotHubClientHandle, &status) == IOTHUB_CLIENT_OK)
            && (status == IOTHUB_CLIENT_SEND_STATUS_BUSY)) {
          IoTHubClient_LL_DoWork(iotHubClientHandle);
          ThreadAPI_Sleep(100);
        }`

This caused the app to hang in this loop. The iot hub client library continued to increase its memory footprint during the course of several hours until the OOM killer was invoked.

When removing the above loop and just invoking the following,

`IoTHubClient_LL_DoWork(iotHubClientHandle);`

the app would continue to add messages to the queue and the iot hub client library continued  to increase the memory footprint during the course of several hours until OOM killer was invoked.

How to reproduce:
- Use the iothub client library with AMQP
- Add a non AMQP port to the hostname in the connection string (e.g. HostName=myiothub.azure-devices.net**:443**;DeviceId=mydeviceid;SharedAccessKey=mysharedaccesskey)

While we expect the send message event to fail when the connection string is invalid, we do expect  the library to properly handle this scenario and not increase its memory usage.

**Comment by tameraw** [comment]
@spr-lfeliu - Thank for filing this issue. We'll investigate it.

**Comment by jtanner-msft** [comment]
Hi @spr-lfeliu,


I wanted to get you a brief update on this.

I’ve begun to look into this, but as I think about it I guess it raised a few questions in my mind where the possibility might exist that someone wants their device clients to communicate via AMQP over a non-standard port.  Perhaps they have to communicate thru a network proxy that only exposes port 80, so they need to send to their own protocol gateway or something like that?  

I guess what I’m trying to say is that while it seems unusual, I can’t say for certain it would be an error if someone offers a unique port number.

With that said, I would agree it could be better handled than an OOM happening, but given the nature of the AMQP communication this might be by design.  Let me continue to look into this and once I have some further thoughts on it I’ll let you know.  For the time being, please make certain to use the correct port numbers.

Thanks,

~Jonathan

**Comment by jtanner-msft** [comment]
Hi @spr-lfeliu ,

So after a little more investigation I agree that the current implementation had a problem in not having an easy way to expose lower level networking errors to the higher layers.

The good news is that we are now adding some retry logic to the SDK which should improve that functionality.

C SDK currently uses the following to two API’s to help understand the behavior of connection underneath.

a.	IoTHubClient_SetConnectionStatusCallback – Using this API you can set callback, which informs you about various states of connection failure particulary look at enum values IOTHUB_CLIENT_CONNECTION_STATUS_REASON
b.	IoTHubClient_SetRetryPolicy – This call can be used to register retry policies and timeout limit up to which SDK will attempt to retry. After the timeout limit is reached, SDK will stop retrying.

The similar two API’s are present for the LL layer as well.

Currently this is only available in the C SDK for MQTT, but look for it to be available in AMQP & HTTP eventually as well.

**Comment by spr-lfeliu** [comment]
Yes, I understand that there may be a need to use a non-standard port. The issue is not with using a non-standard port. The issue is that while it was trying to connect on a closed port, it created a memory leak.

Good to hear, that network errors will be passed to the application. This will be very useful.

Was the cause for the memory leak found? Will the changes you mentioned include a fix for the memory leak?

Thanks.

**Comment by jtanner-msft** [comment]
Hi @spr-lfeliu,

  There is no memory leak happening.  The system was queueing messages so that if a valid connection gets established it could then send them all along.  This was by design for clients that have intermittent connectivity.  But with the implementation of the retry logic you will have more control of having the client error out if after a certain number of messages or time period with no connection is detected.

Thanks,
