### ISSUE TITLE
Microsoft Official IoT WebSite - Pine64 Image

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-iot-sdks#882]
Please consider adding the Pine64 to the Microsoft IoT website & the official image downloads

**Comment by olivierbloch** [comment]
Hi @grahamehorner 
The Pine64 is listed in our Azure Certified for IoT program and shows in the [list of certified devices](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations/).
If you are asking about having it featured on the [Windows IoT Core developer page](https://developer.microsoft.com/en-us/windows/iot), then you will need to reach out to the Windows IoT Core team.

**Comment by olivierbloch** [comment]
@grahamehorner 
I heard back from the Windows IoT Core team and it happens so that the Pine64 is actually listed in the Community Devices section of there device options page: https://developer.microsoft.com/en-us/windows/iot/Explore/deviceoptions
I'll go ahead and close this issue. Feel free to reopen if you have further questions
Thanks
