### ISSUE TITLE
Device Heartbeat

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#893]
How can i get ConnectionState of device as connected when i am sending message and disconnected when i am not sending any message.The below lines are giving device ConnectionState  as disconnected for every device irrespective of sending and receiving messages

RegistryManager registryManager = RegistryManager.createFromConnectionString(connectionString);
System.out.println(device.getConnectionState());

How can i get exact heartbeat from devices 

Could you please send a working code which gives me heartbeat of device whether it is sending message or not so that i can keep track of each device whether it is alive or not

**Comment by olivierbloch** [comment]
Hi @mupparajuvamsi 
As per our [documentation](https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-identity-registry/#device_Heart):
_"The IoT Hub identity registry contains a field called connectionState. You should only use the connectionState field during development and debugging, IoT solutions should not query the field at run time (for example, to check if a device is connected in order to decide whether to send a cloud-to-device message or an SMS)."_

You need to implement the heartbeat pattern in your solution, which means, you need to have your code on the device sending a message at the pace you decide with you content you decide, and have a Cloud app/service that monitors the IoT Hub for this specific message.
