### ISSUE TITLE
[Python] client.send_event_async is blocking!

### ISSUE THREAD

**Issue by zerox1212** [Azure/azure-iot-sdks#898]
I have a project using iot hub sdk for python.

While testing my project I found that `client.send_event_async()` is not actually asynchronous, especially if the internet connection goes down. In some cases this function blocks for almost 20 seconds!

Is this a bug, or is this just a naming misconception and the async portion is actually in the C library, but python still gets blocked?

Screenshot of this function blocking for 18 seconds:
![image](https://cloud.githubusercontent.com/assets/13090472/19742208/864f0612-9b89-11e6-920d-80463a46af03.png)

Using IoT Hub for Python SDK Version: 1.0.16 installed via pip, Windows 7, Python 3.4.4

**Comment by markrad** [comment]
Taking a look at this...

**Comment by zerox1212** [comment]
If you want to reproduce it just use the SDK on a corporate network which blocks AMQP ports.

**Comment by markrad** [comment]
Hi @zerox1212,

Our corporate network doesn't block AMQP ports. However, I will find a mechanism to reproduce it some other way.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @zerox1212,

Currently I am not able to reproduce this. I pulled the network cable during the waiting period in the sample iothub_client_sample.py (I commented out the call to iotHubClient.get_send_status because that would hang). The next sends were queued immediately albeit they weren't sent. When I restored the network the SDK reconnected to the Azure IoT hub and continued as expected.

I'll have to try blocking it with a Firewall rule and see if that makes a difference.

_Mark Radbourne MSFT_

**Comment by zerox1212** [comment]
I will try commenting `get_send_status`.

My full situation is that I'm on a corporate network which blocks all non HTTP ports. It could also be through a proxy. So if I start the client using AMQP I see this blocking shown above. I'll do some more investigation myself just to make sure.

Thanks for investigating.

**Comment by zerox1212** [comment]
I looked and I am not checking send status.

I also forgot to mention that I am trying to send a message every 1 second, although the problem occurs even on the first send.

**Comment by markrad** [comment]
Hi @zerox1212,

I am unable to reproduce this issue. If I block the port on my Windows firewall the Python script spews errors when it attempts to connect to the IoT hub. Having said that though the call to send_event_async still returns almost immediately. Perhaps this is because my port is blocked locally rather than by a device en route. Can you try blocking port 5671 on your Windows firewall and see if your behavior changes? 

_Mark Radbourne MSFT_

**Comment by zerox1212** [comment]
I can try this for you later today. I will report back.

**Comment by markrad** [comment]
Hi @zerox1212 - Any news on this test?

**Comment by zerox1212** [comment]
Sorry, I didn't not have time. I will post here as soon as I can test it.
 Thanks!

**Comment by markrad** [comment]
Hi @zerox1212,

Do you have an update for me?

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @zerox1212,

I have closed this issue due to lack of response.

_Mark Radbourne MSFT_
