### ISSUE TITLE
[CC3200] simplesample_http stops after receiving pending messages.

### ISSUE THREAD

**Issue by cs-motion** [Azure/azure-iot-sdks#909]
I am using the C SDK version 1.0.17 (checked out today). I have installed the tools mentioned in products.mak:

```
XDCTOOLS_INSTALLATION_DIR ?= c:\\ti\\xdctools_3_31_01_33_core
TIRTOS_INSTALLATION_DIR ?= c:\\ti/tirtos_simplelink_2_14_01_20
NS_INSTALLATION_DIR     ?= c:\\ti/ns_1_10_00_00_eng
CC3200SDK_INSTALLATION_DIR ?= c:\\ti/CC3200SDK_1.1.0/cc3200-sdk
ti.targets.arm.elf.M4  ?= c:\\ti/ti-cgt-arm_5.2.5
```

After following the Getting Started instructions for the CC3200, I can build and run the example. After downloading the program to the CC3200 LaunchPad, it successfully connects to the IoT Hub:

```
Starting the simplesample_http example
CC3200 has connected to AP and acquired an IP address.
IP Address: 172.16.2.83
Info: IoT Hub SDK for C, version 1.0.17
IoTHubClient accepted the message for delivery
Message Id: 1 Received.
Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK
Turning fan on.
```

Looks good, but after this moment I can't receive any more messages from the hub. Nothing happens. The only way to receive messages is to restart the board. It will receive any pending messages and after that the program stops again.

I have only modified the example project by entering WiFi settings and the connection string.

If I comment out `ThreadAPI_Sleep(100)` in simplesample_http.c line 233, the program will always receive new messages but then it uses all CPU time instead.

I have used the same ti-rtos version in other sample projects on the same hardware and the OS seems to work fine. In those cases I used the CCS IDE, version 6.2.0. Same toolchain and SDK as above.

I haven't found anyone else having the same issue. Do you have any ideas? :)

**Comment by anhashia** [comment]
Investigating !

**Comment by cs-motion** [comment]
Have you managed to reproduce the problem?

**Comment by anhashia** [comment]
Hi @cs-motion 
Not yet. I am currently working on setting up CC3200

**Comment by anhashia** [comment]
Hi @cs-motion 
I was able to reproduce the issue on TI CC3200. On debugging the issue, I found out that issue is coming from `Seconds_set(ts - (unsigned int) TIMEDIFF)` call in c\serializer\samples\simplesample_http\tirtos\cc3200**\\main.c** 

- For some reason this call to set time in the clock impacts subsequent calls to `Task_sleep` function.  

In other words calling `ThreadAPI_Sleep(100)` call BIOS function `Task_sleep (100)` and it **hangs**. That is why you are not able to receive more messages after this call.

**Workaround** would be comment out (disable) Seconds_set function in main.c file
    ts = mktime(&startTime);
  //  Seconds_set(ts - (unsigned int) TIMEDIFF);

With this change, the sleep function works correctly and calling `ThreadAPI_Sleep(100)`  doesn't hang the device.
Below is the **log** with this change

**Comment by cs-motion** [comment]
Hi @anhashia

This is very nice to hear!

The workaround works on my board as well. Now the sleep function appears to work as expected.

I still need to keep track of the current date and time, but I suppose I can use the clock in the network processor for now.

Thank you so much for your help! :)

**Comment by anhashia** [comment]
Change merged into **develop** branch https://github.com/Azure/azure-iot-sdk-c/blob/develop/serializer/samples/simplesample_http/tirtos/cc3200/main.c

**Comment by anhashia** [comment]
Closing. Please re-activate if you still are having issues. Thanks !
