### ISSUE TITLE
OpenSSL error:14077410

### ISSUE THREAD

**Issue by SYuPing** [Azure/azure-iot-sdks#914]
Hi,

When I tried to load this command

```
wget https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/base/ca-certificates_20160104_all.ipk --no-check-certificate
```
It got this error...

```
root@myYun:/tmp# wget https://downloads.openwrt.org/snapshots/trunk/ar71xx/gener
ic/packages/base/ca-certificates_20160104_all.ipk --no-check-certificate
--2016-11-02 21:52:37--  https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/base/ca-certificates_20160104_all.ipk
Resolving downloads.openwrt.org... 78.24.191.177
Connecting to downloads.openwrt.org|78.24.191.177|:443... connected.
OpenSSL: error:14077410:lib(20):func(119):reason(1040)
Unable to establish SSL connection.
```

I tried to use "curl" instead, but the result is same as above...
How could I solve this?

Thx
[Edited for readability]

**Comment by markrad** [comment]
Hi @SYuPing,

I tried to access the OpenWrt site from my Arduino Yun and encountered the same error as yourself. Since this is not our website, I can't comment on why the Yun is unable to download the ipk of certificates. However I was able to download them on to a Ubuntu desktop and then simply scp them to the Yun for installation. I recommend you try that too.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @SYuPing,

Have you managed to resolve this issue?

_Mark Radbourne MSFT_

**Comment by SYuPing** [comment]
Hi @markrad,

Ya, as your mention, I've solved this problem bu using scp them from linux.
thanks a lot, close this issue.

**Comment by markrad** [comment]
Thank you for letting me know.
