### ISSUE TITLE
SendReceive.java can only send message but its not receiving message

### ISSUE THREAD

**Issue by adiabvs** [Azure/azure-iot-sdks#920]
Hi, 
I am using iot hub sdk java and i have used SendReceive.java to send and receive the message from/to cloud. Messages sent successfully but not received. Generated log is written here.

Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol MQTT.
Successfully created an IoT Hub client.
Successfully set message callback.
Opened connection to IoT Hub.
Beginning to receive messages...
Sending the following event messages: 
Updated token expiry time to 2400
Event Message 0
IoT Hub responded to message 0 with status OK_EMPTY
Event Message 1
IoT Hub responded to message 1 with status OK_EMPTY
Press any key to exit...

**Comment by enuysa-msft** [comment]
Hi @adiabvs,

https://github.com/Azure/azure-iot-sdks/blob/master/java/device/samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/iothub/SendReceive.java file sends messages from Device to Cloud and receives messages from Cloud to Device. 
 So when you are sending messages from Device to Cloud it is normal that you are receiving feedback with iothubstatuscode of OK_EMPTY. because it is just informing that your message is received by IoTHub without message body.

if you want to send message from Cloud to Device you need to use the code in https://github.com/Azure/azure-iot-sdks/blob/master/java/service/samples/service-client-sample/src/main/java/samples/com/microsoft/azure/iot/service/sdk/ServiceClientSample.java So then your messageStatus will be IotHubStatusCode.OK and you will be able to receive the message in https://github.com/Azure/azure-iot-sdks/blob/master/java/device/samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/iothub/SendReceive.java 

I hope this helps you to explain the issue.

**Comment by adiabvs** [comment]
Yes i got it. Thanks
