### ISSUE TITLE
Sending message from DeviceToCloud HTTP Protocol issue in c sdk

### ISSUE THREAD

**Issue by mupparajuvamsi** [Azure/azure-iot-sdks#934]
Hi i am sending message from c sdk code to iothub If I am outside the Corporatte Netwerk I am able to do so .If I am inside the Corporate Network I am facing issue

Error: Time:Wed Nov  9 12:13:41 2016 File:c:\repos\10-14-2016\c\iothub_client\sr
c\iothubtransporthttp.c Func:_DoEvent Line:1597 unexpected HTTP status code (403
)

I am using below lines (iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, HTTP_Protocol)) == NULL for initilization

**Comment by enuysa-msft** [comment]
Hi @mupparajuvamsi 

I believe you are trying the code at https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c 
I have tested it locally and I couldnt find any problem when sending message from DeviceToCloud.

Could you please try to run iothub-diagnostics tool (https://github.com/Azure/azure-iot-sdks/tree/master/tools/iothub-diagnostics) inside the Corporate Network  and inform me with output ?

**Comment by mupparajuvamsi** [comment]
Hi @enuysa-msft 

yes iam using the same code I am facing issue inside the network Can you please let me know which tool you are using to run the code  https://github.com/Azure/azure-iot-sdks/blob/master/c/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c 

And  How to set a flag  to the already read messages from Iothub so that we dont read again again the same data

**Comment by enuysa-msft** [comment]
Hi @mupparajuvamsi 
I have used Visual Studio to run that code

Actually I don't need to set a flag because I dont get again the same data

For Example
I send 3 messages in that C code (see below)
![n1](https://cloud.githubusercontent.com/assets/21202184/20184913/3090c0b4-a762-11e6-9a6b-2f039ae2e31b.png)
I receive 3 messages
![n2](https://cloud.githubusercontent.com/assets/21202184/20184984/541e0456-a762-11e6-8c55-d8803ceb11fa.PNG)
If I send another 2 messages 
![n3](https://cloud.githubusercontent.com/assets/21202184/20185006/624eb728-a762-11e6-85a8-05dacfad8c1d.png)
I am only getting new messages 
![n5](https://cloud.githubusercontent.com/assets/21202184/20185092/b550148a-a762-11e6-8971-4ba3976bfe5e.png)

**Comment by mupparajuvamsi** [comment]
Hi @enuysa-msft 
I am using C code to send messages and Java Program to read messages from DeviceToCloud and Java to send message from Cloud and receive in c program

client.createReceiver( 
	      EventHubClient.DEFAULT_CONSUMER_GROUP_NAME,  
	      partitionId,  
	      Instant.ofEpochSecond(10)).thenAccept(new Consumer<PartitionReceiver>()   the following lines of code If i run the Program again i will get all the messages again.

Still i am facing the issue of HTTP PROTOCOL in my Corporate Network while sending the message with the c code

**Comment by enuysa-msft** [comment]
Hi @mupparajuvamsi 

If you are having issue with HTTP protocol in your Corporate Network then you need to talk with your network security team in your company because maybe some firewalls are blocking to access IoT Hub.
You can try to run iothub-diagnostics tool (https://github.com/Azure/azure-iot-sdks/tree/master/tools/iothub-diagnostics) inside the Corporate Network to check if it is only with Networking issue.

I am testing it with Java and C then I will inform you soon.

**Comment by enuysa-msft** [comment]
Hi @mupparajuvamsi,

I used C code (iothub_client_sample_http.c ) to send messages and Java Program(https://azure.microsoft.com/en-us/documentation/articles/iot-hub-java-java-getstarted/#receive-device-to-cloud-messages) to read messages from DeviceToCloud 

 If i run the Program again i dont get all the messages again.

![s1](https://cloud.githubusercontent.com/assets/21202184/20268827/b099965a-aa78-11e6-847b-c7b08a9d7aab.PNG)

![s2](https://cloud.githubusercontent.com/assets/21202184/20268830/b40e3b42-aa78-11e6-95a2-f2c465f54160.PNG)

**Comment by enuysa-msft** [comment]
Closing. Please re-activate if you still are having issues. Thanks !

@tameraw  Could you please close this?

**Comment by tameraw** [comment]
@mupparajuvamsi - In regards to the issue about tracking the messages in Event Hub so you do not receive them again, please see [this article](https://blogs.msdn.microsoft.com/servicebus/2015/01/16/event-processor-host-best-practices-part-1/).
In regards to the connection issue with HTTP, please follow the initial instruction from @enuysa-msft and run the iothub-diagnostics tool [https://github.com/Azure/azure-iot-sdks/tree/master/tools/iothub-diagnostics](url) inside the Corporate Network and let us know the results.

**Comment by tameraw** [comment]
Let us know if you're still having issues.
