### ISSUE TITLE
Node on Windows set up

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdks#96]
In reference to this section:

_If you are using Windows, open the Node.js command prompt, then navigate to the node\build folder in your local copy of this repository (azure-iot-sdks). Then run the build.cmd script to verify your installation._

Execution of the build.cmd will now fail. This is caused by downloading and installing the latest and greatest node from node.org which has now undergone a major version change. It is now known as v4.2.1. Error message as follows:

_C:\Users\markrad\Source\Repos\azure-iot-sdks\node\build>build.cmd_
_Checking Node.js version: ._
_jake aborted._
_Error: Incorrect Node version. Expected within range 0.12.x, but was v4.2.1._
        _at api.fail (C:\Users\markrad\Source\Repos\azure-iot-sdks\node\build\node_modules\jake\lib\api.js:336:18)_
    _at Object.exports.check (C:\Users\markrad\Source\Repos\azure-iot-sdks\node\build\lib\version_checker.js:9:10)_
_(See full trace by running task with --trace)_

**Comment by tameraw** [comment]
We are looking into it.

**Comment by markrad** [comment]
By the way, if one modifies the required version in the package.json it does work as expected with v4.2.1

**Comment by damonbarry** [comment]
This was fixed in our latest release to master (https://github.com/Azure/azure-iot-sdks/tree/v1.0.0-preview.4).  If you look in /node/build/package.json you'll see the following:

    "engines": {
        "node": "^0.12 || ^4"
    },

We made similar changes in the other package.json files as well so that the build doesn't get hung up on the version check.  Also, in the develop branch we've removed the Node.js version check entirely, so in the future you won't see this problem.
