### ISSUE TITLE
[Android][MQTT] Can't close DeviceClient to open a new connection if MQTT connection is lost.

### ISSUE THREAD

**Issue by cdpwind** [Azure/azure-iot-sdks#961]
Hi,

When MQTT connection is lost, DeviceClient.close is not working.
If it is called by my app, there is no return, it seems locking in somewhere.

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Hi @cdpwind 
I wasn't able to reproduce the issue.
Can you please provide more **details** on  reproduction steps so that I can locally reproduce the issue.  If you can provide answers to below questions that would help.

1.) Which Android version are using ?
2.) Which  iothub-java-device-client library are using ? If you can using old one can you please re-test with latest available iothub-java-device-client: **1.0.15**
3.) Exact repro steps. 
4.)  Do you see the issue during sending of C2D messages or receiving of message ?
5.)  Does the issue have 100% reproduction ? If not, what is the repro rate ?
6.) Does  https://github.com/Azure/azure-iot-sdks/tree/master/java/device/samples/android-sample that come with Azure IoT SDK also show the same issue ? If you have not tried on it, can you please try the scenario with this sample and see if you are able to reproduce the issue. I am using the same sample for local reproduction of the issue.
7.) Does the issue happen on Android emulator also ?

**Comment by cdpwind** [comment]
Hi,
First of all, thank you for your efforts to resolve my issue.

1) 5.1 and 4.4.2

2) currently, 1.0.14. i'll try to test it with the latest version, 1.0.15.

3) It is very simple to reproduce this issue on your test environments.
  [1] Register new device to Azure IoThub and prepare a connection string.
  [2] launch you app and open a connection which is set with a message callback to handle a message from server, azure. this connection should be opened with a connection string that made at step [1]
  [3] Delete registered device from IoThub. it means a connection string is now invalid.
  [4] You can see this issue on your test environments.

4) No. This issue is not related to sending message. I was set the message callback to receive a message from server, AZURE. i think, it relate to a background thread to receive a message from server.

5) 100% reproducible.

6) Yes.

7) I'm not sure, but it is same in my guess.

For more detail to your understanding,
We need a method to invalidate registered device. currently for doing it, we used "Delete registerd device from Azure Iothub".
If you have another solution, please guide me.

Thanks.

**Comment by cdpwind** [comment]
Hi,

I've tried to test this issue with the latest version of library, 1.0.15.
The result is same.

If below exception is occurred, DeviceClient.close() method doesn't working, no return, it seems deadlock.

11-23 13:47:53.518 31230-31827 I/System.out: java.lang.IllegalStateException: The MQTT connection is currently closed. Call open() before attempting to receive a message.: The MQTT connection is currently closed. Call open() before attempting to receive a message.

Only one solution to resolve this issue is just restart app.

**Comment by anhashia** [comment]
Hi @cdpwind 
I am still not clear about how you are removing the device. Are your trying to close the device which has already been removed ?

The way to **remove** the device from the registry would be to make following calls in you application

````````
RegistryManager registryManager = RegistryManager.createFromConnectionString(SampleUtils.iotHubConnectionString);
registryManager.removeDevice(SampleUtils.deviceId);

``````````

Use following sample as reference.
java\service\samples\device-manager-sample\src\main\java\samples\com\microsoft\azure\iot\service\sdk\ **DeviceManagerSample.java**

https://azure.github.io/azure-iot-sdks/java/service/api_reference/com/microsoft/azure/iot/service/sdk/RegistryManager.html#removeDevice-java.lang.String-

**Comment by cdpwind** [comment]
Hi @anhashia,

I've used "Device Explorer" application on Windows to remove a device from IoTHub of AZURE.
As you know, perhaps some devices(my app) should be invalidated on our service, this action is not performed by itself(my app). maybe administrator will be do it with some methods, currently it is "Device Explorer".

**Comment by anhashia** [comment]
Hi @cdpwind 
If your delete it via **Device Explorer** and then try to connect on a device identity that no longer exists, you will get following exception in your Java application

```
I/System.out: Exception while opening IoTHub connection: java.io.IOException: Error initializing MQTT connection:Not authorized to connect
````

So what is your sequence of events that results in hang in close ?
Are you deleting a device identity via **Device Explorer**  that is being currently in use by the other application ?

**Comment by cdpwind** [comment]
Hi @anhashia,

I know that "Not authorized" message is occurred when new connection is established.

In my case,
1) connecting to IoThub with a valid connection string to receive some message from server.
2) a connection is still alive.
3) and then, delete a device via "Device Explorer" to invalidate a connection string.
4) Huge error messges are occurred. if you try to close DeviceClient to stop an error, DeviceClient.close method does not return forever.

Can you reproduce above situation in your side?

**Comment by anhashia** [comment]
Hi @cdpwind 
I was able to reproduce the issue locally on my side using an Android emulator with your latest reproduction steps.

**Root Cause**
When you delete or disable  a **connected** device identity through a Device Explorer too , it will send a disconnect notification to the connected client and hit following code running in another thread.
``
 public void connectionLost(Throwable throwable)
``
``
\java\device\iothub-java-client\src\main\java\com\microsoft\azure\iothub\transport\mqtt\MqttIotHubConnection.java
``

Since the device was **connected** in first place and it lost connection all of sudden, it will assume it to because of network issue (transient error) and it will retry. it will acquire the lock and try to do a **retry**. Currently retry is for a **transient error**  and it will keep on trying. In you particular case, retry won't help because you have already deleted your device identity. That use case is not there right now. 

When you then try to close the connection on another thread, there is a deadlock as lock is held by retry thread and it will keep on retrying.  Below will be the state of thread 

Close connection is blocked
``````
<1> main@831887064232" prio=5 waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	  at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.close(MqttIotHubConnection.java:151)
	  at com.microsoft.azure.iothub.transport.mqtt.MqttTransport.close(MqttTransport.java:104)
	  at com.microsoft.azure.iothub.DeviceClient.close(DeviceClient.java:219)
````````

Retry thread is waiting
````````
"<13> MQTT Rec: MyDevice5@831891144136" prio=5 sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.VMThread.sleep(VMThread.java:-1)
	  at java.lang.Thread.sleep(Thread.java:1013)
	  at java.lang.Thread.sleep(Thread.java:995)
	  at com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.connectionLost(MqttIotHubConnection.java:294)
`````````

**Possible workaround**
Retry feature is work in progress. There is also an active bug #949 against it.  To avoid this type of issue, for now the workaround would be not to delete the device identity object with the backend application if it is being reported in the connected state.

**Comment by anhashia** [comment]
@ #949

**Comment by anhashia** [comment]
Retry feature is being improved upon and is being tracked with Product Backlog Item (PBI)

**Comment by cdpwind** [comment]
Hi @anhashia, 
I've found missed your questions.

a.) Are you deleting a device identity that is currently in connected state from Device Explorer ? Why would you (admin) delete a device that is currently in an established MQTT session (trying to understand the use case here) ? One possible workaround would be wait till device is in disconnected state before deleting it.
-> Yes, you're right. If admin do something to send a disconnect command to my app before deleting a deviceId, this issue does not occurred.
As i said, "Delete a deviceId via Device Explorer" is temporary method to invalidate a device(my capp). 
Currently, we are finding other method to do it.

b.) Are you then trying to close the DeviceClient for deviceID in the application that was just deleted by admin (which was in previously connected state) ?
-> Yes, i did. maybe the state of DeviceClient is open at that time because there is no method to check the state of DeviceClient. Of cause, no event does not escalated from IoThub library and no method to listen it.
Continuing above my answer.
On my position as app developer, my app must have an exception handling related to this issue because nobody can give a guarantee that a DeviceId will not deleted during session is alive. 
But this issue can't be controlled by my app if already occurred.
So this issue is critical to me.

**Comment by anhashia** [comment]
Hi @cdpwind 
Yes, this issue/ scenario is looked at and is tracked with a Product Backlog Item (PBI) by Product team developer. This will be looked under **retry** feature as the hang is coming because the retry code keeps on trying as it assumes it disconnection because of **transient error**.  Since retry thread holds the lock, close thread is waiting for the lock to be released and hence you see the issue.
I have tagged the issue as "added to backlog".

**Comment by taruntak** [comment]
@anhashia @cdpwind 
How to Register new device to Azure IoThub in Android?
I am using  compile 'com.microsoft.azure.iothub-java-client:iothub-java-device-client:1.0.16'

**Comment by anhashia** [comment]
HI @taruntak 
For registering a device, you need `addDeviceAsync` method from RegistryManager
class. For that you need service side SDK

Use following for reference
https://azure.github.io/azure-iot-sdks/java/service/api_reference/com/microsoft/azure/iot/service/sdk/RegistryManager.html

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#22
