### ISSUE TITLE
[Java] Unclear behavior for C2D Message Feeback

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdks#968]
While debugging [the Service SDK sample](https://github.com/Azure/azure-iot-sdks/blob/master/java/service/samples/service-client-sample/src/main/java/samples/com/microsoft/azure/iot/service/sdk/ServiceClientSample.java) I noticed that the feedback returned by the SDK is not specific to the messages sent.

How to reproduce:
* Run the sample code a few times (e.g. 10)
* Debug the sample code with a breakpoint on line 76 (after `FeedbackBatch feedbackBatch = future.get();`)
* Note that `feedbackBatch.records` includes only 1 record
* Inspect `feedbackBatch.records.get(0).originalMessageId`
* Inspect `messageToSend.messageId`

The 2 message IDs are not the same, so I assume the feedback doesn't include information about the message sent by the current run, but instead the feedback for a message sent during one of the previous executions.

1. Could you clarify this behavior, is it documented?
2. Should a client request the feedback multiple times until it gets the right one?
3. Why doesn't the batch include the feedback for all the messages sent?

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Hi @dluc 
There is an issue with monitoring feedback in Java Service client and Product Backlog Item (PBI) will be created to track and fix this. When a device completes the processing of feedback message, it has to notify IoT Hub that message has been processed so that it is removed from the message queue. That is not currently happening in Service side SDK sample.

Message life cycle is covered under following link
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging

**Comment by tameraw** [comment]
Captured in backlog to provide CompleteAsync feature.

**Comment by tameraw** [comment]
This issue was moved to Azure/azure-iot-sdk-java#20
