### ISSUE TITLE
Clock / Time sync requirement for RTOS based device to connect IoT Hub?

### ISSUE THREAD

**Issue by bhalgat20** [Azure/azure-iot-sdks#987]
Hi,

This is regarding “Connecting RTOS based devices to Azure IoT Hub using Device client ‘C’ sdk”.
As per our understanding, device needs to know current time to establish connection with Azure IoT hub.
The azure IoT SDK requires the current time from the platform for deriving the expiration time for the token(in current implementation it is set to 1hour).

httpapiexsas.c

HTTPAPIEX_RESULT HTTPAPIEX_SAS_ExecuteRequest(HTTPAPIEX_SAS_HANDLE sasHandle, HTTPAPIEX_HANDLE handle, HTTPAPI_REQUEST_TYPE requestType, const char* relativePath, HTTP_HEADERS_HANDLE requestHttpHeadersHandle, BUFFER_HANDLE requestContent, unsigned int* statusCode, HTTP_HEADERS_HANDLE responseHeadersHandle, BUFFER_HANDLE responseContent)
{
…
   size_t expiry = (size_t)(difftime(currentTime, 0) + 3600);
                    STRING_HANDLE newSASToken = SASToken_Create(state->key, state->uriResource, state->keyName, expiry);

We have RTOS based devices which does not have rtc(real-time clock) and NTP client implementation yet. 
Do we have any alternative option? Can we skip the clock requirement for RTOS based devices and still successfully make handshake with IoT Hub?

Thanks,
Ashish

**Comment by dcristoloveanu** [comment]
Like you observed time is used for 2 things:
- Validate the validity of the IoTHub certificate (specifically the expiry time of the certificate) so that the TLS tunnel is established.
-Generate SAS tokens so that the identity of the device on the wire is limited as lifetime. If a SAS token is intercepted that identity can be used to spoof the device only until the token expires.

Not having time on the device directly results on these 2 points being invalidated.

What can be done (but it is NOT RECOMMENDED) is:
- Disable the certificate validation on the device. Each TLS stack that we use has an option to do such, but we purposely do not expose that in the client API, so you would have to go and change this in the code and rebuild.
- Set a very long lifetime for the SAS token or change the code to hardcode an expiry time on the token.

By doing these you open up to security issues, thus we strongly recommend to implement an NTP client in the device and by that get real time that can be used for these 2 tasks.

I hope this helps,
/Dan
