### ISSUE TITLE
How to check that device is online?

### ISSUE THREAD

**Issue by bartoszbr** [Azure/azure-iot-sdks#988]
Hello, I have read your articles about how to check that device is online:
https://docs.microsoft.com/pl-pl/azure/iot-hub/iot-hub-guidance#heartbeat        
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#device_Heart
and I also have read previous issue about this topic on GitHub:
https://github.com/Azure/azure-iot-sdks/issues/893

After that I have a few questions:
Why using field called connectionState is bad idea? On my short tests it worked perfect. 
I found information that we can achieve the same result by setting short expiry time. 
Sending a message Cloud 2 Device I set ExpiryTimeUtc to DateTime.Now.AddSeconds(1) and I set feedback timeout to 1 sec ( await feedbackReceiver.ReceiveAsync(TimeSpan.FromSeconds(1)) ).
There is a problem, because I have to wait for feedback with data about 10-15 seconds (ReceiveAsync gives callback with null every second).
Is there any option to configure feedback to send data every callback instead a batch of data for 10-15 seconds?

There is also opportunity of using HeartBeat pattern. 
I can send messages from devices to cloud, but it can make problems with operation throttles (using IoT hub). I can also use my own HeartBeat mechanism - to send messages to other service, but Im looking for other solutions.
Can you suggest me the best way to do that?

**Comment by fsautomata** [comment]
Hi bartoszbr,

The ConnectionState property is not guaranteed to be reliable, which means that there are instances where it is not updated. It is intended for debugging/dev scenarios.

If you want to check reliably if a device is online the best option is probably to use a direct method (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods).

If you want to maintain a registry of the "health" of the devices, you can use twin reported properties.
Since twin is a reliable store, this could prove too expensive for your solution, in that case you can try to optimize by sending D2C messages and storing them is an unreliable cache (such as REDIS).

**Comment by bartoszbr** [comment]
fsautomata, thanks for your reply. 
Direct methods look promising, but I'm affraid that I have to use C# language on devices, so I can't use direct methods because implemetation of using it in SDK for C# isn't ready yet. I found workaround of it:  https://social.msdn.microsoft.com/Forums/expression/en-US/eb86d187-af89-4d8a-bdc4-97d440e8d918/invoke-a-direct-method-on-a-device-preview?forum=azureiothub 
but I prefer use offical MS release and my client requires using AMQP - this workaround is just for MQTT.

**Comment by fsautomata** [comment]
Support for AMQP and C# for methods is coming out very soon.
Stay tuned.

**Comment by Sneezry** [comment]
Microsoft.Azure.Devices.Client SDK (version 1.1.4) in C# should have already supported direct method, right?

**Comment by damonbarry** [comment]
Yes, it does.

**Comment by damonbarry** [comment]
Closing this issue. Feel free to reopen in [azure-iot-sdk-csharp](https://github.com/Azure/azure-iot-sdk-csharp) if needed.
